NeuralEnsemble/python-neo

neo/io/baseio.py, neo/io/plexonio.py
- Times and labels (i.e. event codes) for event data are now accessible in an EventArray object that belongs to a given Segment object. 
- Annotations for segment and spiketrain objects now include all properties found in their respective file and spike channel headers (see [documentation](http://hardcarve.com/wikipic/PlexonDataFileStructureDocumentation.pdf)).
- A host of typos and style have been fixed to make the code more readable.
=> Plexon IO class changes

neo/io/hdf5io.py
Right now, no matter the `dtype` of the `AnalogSignal`, the EArray is created as a float64. This leads to unnecessarily large files. This PR allows the user to set whether to respect the dtype of the Arrays.
=> Don't force EArray type to float64.

.gitignore, doc/source/install.rst, neo/core/analogsignalarray.py, neo/io/__init__.py, neo/io/axonio.py, neo/io/baseio.py, neo/io/blackrockio.py, neo/io/blackrockio_deprecated.py, neo/io/brainvisionio.py, neo/io/hdf5io.py, neo/io/neomatlabio.py, neo/io/neuroscopeio.py, neo/io/neuroshareapiio.py, neo/io/neurosharectypesio.py, neo/io/plexonio.py, neo/io/pynnio.py, neo/io/spike2io.py, neo/io/tdtio.py, neo/test/coretest/test_analogsignalarray.py, neo/test/iotest/test_axonio.py, neo/test/iotest/test_blackrockio.py, neo/test/iotest/test_blackrockio_deprecated.py, neo/test/iotest/test_brainvisionio.py, neo/test/iotest/test_neuroshareio.py, neo/test/iotest/test_spike2io.py
With this update, I think we are ready for the next round of api-breaking changes.
=> Merged recent changes in "master" into "apibreak"

neo/io/neuroshareapiio.py, neo/test/iotest/test_neuroshareio.py
=> Try to fix issue #200.

neo/io/axonio.py
Bug fix for ABF fiels when fSynchTimeUnit is not 0.
=> Error in t_start when fSynchTimeUnit is not 0.

neo/io/spike2io.py
Right now, if you sorted spikes with spike2, Spike2 will attach a unit number to each spike using the first marker byte, indicating which unit generated the spike. However, when reading the smr file, neo ignores the units and only creates a single SpikeTrain pretending as if the spikes all come from a single unit.
This adds a `ced_units` keyword, which when true, will create a SpikeTrain for each unit. Otherwise, the default, will just create a single SpikeTrain ignoring units like before. It also adds a `ced_unit` keyword to the annotations distracting from which Spike2 unit this SpikeTrain was generated.
=> Optionally include Spike2 sorted unit tags in SpikeTrain.

neo/io/spike2io.py
=> Try to fix issue #230 problem of i2 instead of i4 in channel header.

LICENSE.txt
Add a bullet point for the 3rd clause of the license.
=> License format adjustment

neo/io/igorproio.py, neo/test/iotest/test_igorio.py
Replaces #225 (pull-request against master, instead of apibreak branch).
Awaiting upload of test files to G-Node.
=> Added an IO for IGOR Pro.

neo/core/epoch.py, neo/core/event.py, neo/core/irregularlysampledsignal.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py, neo/test/coretest/test_irregularysampledsignal.py
=> #60 Time_slice() added in epoch, event and irregularsampledsignal

neo/io/__init__.py, neo/io/nestio.py, neo/test/iotest/test_nestio.py
Adding an IO, which reads gdf and dat files as they are generated by NEST. This is an alternative implementation to the IOs suggested by @apdavison in PR #299.
=> Add nestio

neo/io/blackrockio.py
* lazy very fast
* fix lazy problem (because anasig.signal=[] do not work)
* put float32 as default instead of float
* fix int overflow
=> Some fix for BlackrockIO v4

neo/io/__init__.py, neo/io/neuralynxio.py, neo/test/iotest/test_neuralynxio.py
Adding an IO which reads standard Neuralynx output files in ncs, nev, nse and ntt format. First ones are  tested, for later ones there are currently no test files available.
=> Add NeuralynxIO

neo/io/blackrockio.py
This pull request is equivalent to this PR that I closed: https://github.com/NeuralEnsemble/python-neo/pull/325 but with a cleaner commit history.
=> Minor Fixes to the Blackrock reader

neo/core/spiketrain.py, neo/test/iotest/test_pickleio.py
=> Ensure that SpikeTrains do not lose their parent objects on pickle

neo/io/micromedio.py, neo/test/iotest/test_micromedio.py
=> Quite and dirty fix for Denis bug.

neo/version.py
A error on top of an error...
This should correct.
=> Version error

neo/core/channelindex.py
This PR updates the documentation of the `neo.ChannelIndex` class based on discussions in issues https://github.com/NeuralEnsemble/python-neo/issues/309 and https://github.com/NeuralEnsemble/python-neo/issues/350 and offers a new starting point to clarify the intended use of `neo.ChannelIndex` objects and directly update the corresponding documentation. I would be happy about some feedback and suggestions / for additional use cases to include in the docstring.
=> Clarify usage of ChannelIndex objects

neo/io/axonio.py, neo/io/elanio.py, neo/io/micromedio.py, neo/io/neuralynxio.py, neo/io/plexonio.py, neo/io/rawbinarysignalio.py, neo/io/spike2io.py, neo/io/tdtio.py, neo/io/winedrio.py, neo/io/winwcpio.py, neo/test/iotest/test_elanio.py, neo/test/iotest/test_micromedio.py, neo/test/iotest/test_plexonio.py, neo/test/iotest/test_tdtio.py
Various fixes for for some IOS:
* PlexonIO : #372 
* ElanIO: py3
* MicromedIO
* TdtIO
* Spike2IO
* WinEdrIO
* WinWCPIO
* RawBinarySignalIO
* NeuralynxIO
=> Various fixes for some IOs

neo/core/analogsignal.py, neo/core/basesignal.py, neo/core/irregularlysampledsignal.py
Preliminary version of a parent mixin class for `AnalogSignal` and `IrregularlySampledSignal` -- Issue #381
=> Preliminary version see #381

doc/source/authors.rst, neo/io/tdtio.py, neo/rawio/tdtrawio.py
=> Tdtraw fixes

neo/io/basefromrawio.py, neo/rawio/baserawio.py
When creating the objects in BaseFromRawIO.py I added the parameter file_origin everytime an object is created. The value of this is taken from self._source_name(). Now every object contains the attribute file_origin and this is not None.
=> Added file origin to all neo objects when using RawIO API

neo/core/analogsignal.py, neo/core/epoch.py, neo/core/event.py, neo/core/irregularlysampledsignal.py, neo/core/spiketrain.py, neo/io/igorproio.py, neo/test/coretest/test_block.py
=> Implements `__deepcopy__` for all data classes

neo/io/basefromrawio.py, neo/test/iotest/test_blackrockio.py, neo/test/iotest/test_exampleio.py, neo/test/iotest/test_neuralynxio.py
=> Remove time_slices from read_block in BaseFromRaw

neo/io/spike2io.py, neo/rawio/spike2rawio.py, neo/rawio/tests/test_spike2rawio.py, neo/test/iotest/test_spike2io.py
=> Fix multi sampling rate in Spike2IO

neo/io/kwikio.py, neo/test/iotest/test_kwikio.py
=> Re-enable KwikIO tests after uploading new test files

CITATION.txt, README.rst, doc/source/index.rst
=> Add citation information to README and to docs.

neo/test/iotest/test_neuralynxio.py
* remove outdated time_slice keyword
* fix channel_index access
=> [MRG] Fix neuralynx tests

neo/rawio/axonrawio.py
=> [MRG] Stupid bug.

neo/io/klustakwikio.py, neo/test/iotest/test_klustakwikio.py
=> [MRG] Make KlustaKwikIO py3 compatible. Fix for #467

doc/source/io.rst, doc/source/releases/0.6.0.rst, neo/io/basefromrawio.py
[doc] add comment about lazy being deprecated
=> [MRG] more documentation updates

neo/rawio/axonrawio.py
=> This should fix #511

neo/rawio/winwcprawio.py
Fix bug "error: [Errno 24] Too many open files".
Open only one memmap for all segmengts.
issue #515
=> [MRG] Fix bug "error: [Errno 24] Too many open files".

neo/io/elphyio.py, neo/test/iotest/test_elphyio.py
- fix outdated imports
- fix py3 compatibility
- reintroduce tests
=> [MRG] Update elphyio

neo/rawio/spike2rawio.py
=> Strong bug in Spike2IO.

setup.py
Addresses issue #519, where using a too old version of nixio will cause importing Neo to fail.
=> Added minimum version to nixio

neo/rawio/neuralynxrawio.py
We have multiple records, where some channels are missing, i.e., they have only the header in it. Therefore the pull request
=> filter empty files while reading in neuralynxrawio.py

neo/core/analogsignal.py, neo/core/irregularlysampledsignal.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_analogsignalarray.py, neo/test/coretest/test_irregularysampledsignal.py
=> [WIP] Fix for #556

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
according to the discussion in #369.
When adding and subtracting Quantity scalars, `t_stop` and `t_start` are also modified by the amount of the scalar.
When adding and subtracting Quantity arrays, `t_stop` and `t_start` are not modified unless some of the new spike times fall outside the range [t_start, t_stop], in which case the range is extended to include all spikes.
(This is a combination of Options 3 and 4 in Problem 2 in #369, which I think addresses all the concerns expressed in the discussion).
Attempting to add or subtract two SpikeTrains raises a TypeError, except for the case of subtracting two SpikeTrains of the same size, in which case a Quantity array is returned (Option 3 in Problem 1)
=> Change the behaviour of `SpikeTrain.__add__` and `SpikeTrain.__sub__`

neo/io/__init__.py, neo/io/intanio.py, neo/rawio/__init__.py, neo/rawio/intanrawio.py, neo/rawio/tests/test_intanrawio.py, neo/test/iotest/test_intanio.py
This rawio class implement both intan tec RDH and RHS.
It was more difficult that I thought because it handles multiple signals sampling rate and signal size!!
=> Intanrawio : both RHD and RHS

neo/core/epoch.py, neo/core/event.py, neo/io/nixio.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py, neo/test/coretest/test_generate_datasets.py, neo/test/generate_datasets.py, neo/test/iotest/test_pickleio.py
=> add `Event.to_epoch` method

neo/rawio/spike2rawio.py
=> rtu to fix this overflow.

doc/source/releases/0.7.0.rst
=> Add new AxographIO to 0.7.0 release notes

doc/source/releases/0.7.0.rst
Sorry about the multiple pull requests, but @will-hart did nearly all of the work on #550, so I'd be remiss if I didn't try to add him here!
=> Add contributor to 0.7.0 release notes

neo/io/basefromrawio.py
This must be merged before #617
=> Fix bug in basefromrawio for annotation in ChannelIndex.

neo/io/blackrockio.py, neo/rawio/blackrockrawio.py, neo/rawio/tests/test_blackrockrawio.py, neo/test/iotest/test_blackrockio.py, neo/version.py
Started just after Palermo codejam.
This is proof of concept.
Need be tested.
=> Blackrock multi ns x

.circleci/config.yml, neo/core/basesignal.py, neo/core/irregularlysampledsignal.py, neo/test/generate_datasets.py, requirements.txt
Some of them are due to Neo problems, one is a NumPy 1.16.0 bug
=> Fix some test failures that recently appeared on CircleCI

neo/test/iotest/test_brainwaredamio.py, neo/test/iotest/test_brainwaref32io.py, neo/test/iotest/test_brainwaresrcio.py
(see https://github.com/numpy/numpy/releases/tag/v1.16.3)
=> Fix for error encountered when using NumPy 1.16.3

neo/test/test_utils.py, neo/utils.py, utils.py
Addresses #526. I added [neo_utils.py](https://web.gin.g-node.org/INT/multielectrode_grasp/src/master/code/neo_utils.py) as `neo/utils.py` as suggested in https://github.com/NeuralEnsemble/python-neo/issues/526#issuecomment-431916318. I ensured compatibility with the current version of neo, especially with proxy objects to get the functionality outlined in https://github.com/NeuralEnsemble/python-neo/issues/526#issuecomment-383529750, and added unittests.
The original had a header with copyright information, a disclaimer, etc. I guess this is not needed since you have corresponding info for neo as a whole, right?
=> Added utility module neo/utils.py

neo/test/iotest/test_proxyobjects.py
=> Add tests for BaseProxy.time_slice

doc/source/authors.rst, doc/source/conf.py, doc/source/core.rst, doc/source/examples.rst, doc/source/io_developers_guide.rst, doc/source/rawio.rst, doc/source/releases/0.7.1.rst, doc/source/releases/0.7.2.rst, doc/source/whatisnew.rst, neo/io/__init__.py, neo/io/asciisignalio.py, neo/io/axonio.py, neo/rawio/__init__.py, neo/rawio/examplerawio.py
This PR also includes fixes to the docs to eliminate warnings issued by Sphinx.
=> Add missing release notes for 0.7.1 and 0.7.2

doc/source/authors.rst, doc/source/conf.py, doc/source/core.rst, doc/source/examples.rst, doc/source/io_developers_guide.rst, doc/source/rawio.rst, doc/source/releases/0.7.1.rst, doc/source/releases/0.7.2.rst, doc/source/whatisnew.rst, neo/io/__init__.py, neo/io/axonio.py, neo/rawio/__init__.py, neo/rawio/examplerawio.py
=> Backport missing release notes for 0.7.1 and 0.7.2

neo/rawio/nixrawio.py, neo/test/iotest/test_nixio_fr.py
Dealing with issue #625 
now the NixIOFr will read customize annotations
=> [NixIOFr] adding support for customize annotations 

neo/io/baseio.py, neo/io/tools.py, neo/test/coretest/test_base.py, neo/test/coretest/test_dataobject.py
=> Fix some deprecation warnings

neo/io/spike2io.py, neo/rawio/spike2rawio.py, neo/test/iotest/test_spike2io.py
Option in Spike2io for grouping channel with same sampling rate
=> Option in Spike2io for grouping channel with same sampling rate

neo/core/analogsignal.py, neo/test/coretest/test_analogsignal.py
=> Time slice consistency

neo/rawio/nixrawio.py, neo/test/iotest/test_nixio.py
There seems to be an issue with the NIXRawIO that was introduced through PR #629 but only showed up when both that PR and #702 were merged.  I'm currently working to fix it, but as I understand the failing test is blocking other PRs from being merged.  I've disabled the test while I work on the core issue to keep other PRs from being merged.
=> [NIXIO] Disable lazy load test

neo/rawio/blackrockrawio.py
=> Issue from histed@github.

neo/io/basefromrawio.py
=> Warning for signal group mode.

neo/rawio/openephysrawio.py
fixes issue where openephysrawio reader ignores aux and adc .continuous files specified by the current/old open ephys format.
=> read all .continuous files

neo/rawio/neuralynxrawio.py, neo/test/iotest/test_neuralynxio.py, neo/test/rawiotest/test_neuralynxrawio.py
This is just a rebased version of #693 
The previous PR became eventually broken when I had reset it and used rebase instead of merge.
=> REBASED Nlx lost segments with lost samples 

doc/source/authors.rst, doc/source/releases/0.8.0.rst, doc/source/whatisnew.rst
First drafty list for release 0.8.0
=> Draft for release.

neo/rawio/bci2000rawio.py
=> Enhance bci2000 header parsing

setup.py
Fixes #769.
I also updated the PyPI classifiers to declare compatibility with Python 3.7 and 3.8.
=> Update requirements in setup.py to match requirements.txt

neo/rawio/openephysrawio.py
=> STring bug in openephysio.

neo/utils.py
This is a first change in a list of adjustments that need to be implemented in the utility functions to fully make use of the new array_annotation feature.
[edit] This PR also removes the notion of treating regular annotations that are lists of the shape of the data like array annotations. For this purpose array annotations should be used.
=> Improve utilities

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Bug introduced in #695 (as a fix for #694).
See #771.
=> [nixio] Fix channel name reading

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Rebased and cleaned the branch for PR #760.
=> NIXIO ImageSequence support

neo/rawio/bci2000rawio.py
=> Clean gain for some files because it can be numerical or string.

neo/io/basefromrawio.py
=> Handling load_waveforms params when lazy load.

neo/rawio/axonrawio.py
This fix a small bug inherented from old code (whan porting to rawio) I think.
=> fix axonio channel events bug.

neo/utils.py
This implement proof of concept for #828.
@JuliaSprenger @achilleas-k : please make coments when you have time.
=> Add is_block_rawio_compatible() in neo.utils

neo/rawio/baserawio.py
Fixed one error in exception name. Corrected typos in comments.
=> Correct typo in exception name and in typos in comments.

neo/core/analogsignal.py, neo/core/imagesequence.py, neo/test/coretest/test_analogsignal.py
(also note: this inspired the creation of #857)
=> Fixes #757

neo/io/axographio.py, neo/io/axonio.py, neo/io/basefromrawio.py, neo/io/bci2000io.py, neo/io/brainvisionio.py, neo/io/elanio.py, neo/io/neuroexplorerio.py, neo/io/nixio_fr.py, neo/io/plexonio.py, neo/io/rawbinarysignalio.py, neo/io/tdtio.py, neo/io/winedrio.py, neo/io/winwcpio.py, neo/test/iotest/test_axographio.py, neo/test/iotest/test_exampleio.py
'split-all' > 'group-by-same-units'
#715
#832 
#710
=> Default group mode to 'group-by-same-units'

neo/io/axographio.py, neo/test/iotest/test_axographio.py
=> [axographio] Add test for group-by-same-units

LICENSE.txt, README.rst, doc/source/conf.py, doc/source/core.rst, doc/source/grouping.rst, doc/source/releases/0.9.0.rst, doc/source/whatisnew.rst, neo/core/view.py, neo/version.py
=> Release notes for v0.9.0

.circleci/config.yml, neo/test/rawiotest/tools.py
This PR is opened to test if CircleCI tests will be triggered. The actual PR is #919.
=> [WIP] Triggering CI

doc/source/authors.rst, neo/io/basefromrawio.py, neo/test/iotest/common_io_test.py
=> Fix multiples errors in BaseFromRaw.read_block()

neo/test/rawiotest/test_neuralynxrawio.py
Follow up of #957 to catch up with changes introduced in #949
=> [neuralynx] Adjust test to match #949

neo/utils/datasets.py
This PR improves the fetching of testing data from gin by
- ensuring local changes are reset
- the master branch is used for testing
- new files are pulled
@samuelgarcia What do you think?
=> [datalad] fix fetching of incomplete / new data from gin

neo/test/iotest/test_neuralynxio.py
=> [neuralynx] reintroduce spiketime and recording trace tests

neo/rawio/nixrawio.py, neo/test/iotest/test_nixio_fr.py
This PR adds support for annotations and array annotations for signals on NixIOfr level.
=> Signal array annotations in NixIOfr

neo/rawio/openephysbinaryrawio.py
=> oephys handle "Experiment"

neo/rawio/maxwellrawio.py
Fixes https://github.com/NeuralEnsemble/python-neo/issues/1073
=> Sort and re-sort maxwell indices in case they are not sorted

neo/io/proxyobjects.py, neo/rawio/openephysbinaryrawio.py
@samuelgarcia This branch is a collection of tiny code improvements not directly linked to any other PR. Feel free to add or merge whenever you want.
=> Minor code improvements

neo/rawio/openephysrawio.py
See #1055, waiting for feedback
=> Fix OpenEphys bug stream ids #1055

neo/io/nixio.py, neo/test/iotest/test_nixio.py
=> [nixio] fix quantity property handling and add test

neo/core/spiketrainlist.py, neo/test/coretest/test_spiketrainlist.py
bug fix for annotations plus more consistent interface
=> SpikeTrainList improvements

neo/io/neurosharectypesio.py, neo/test/iotest/test_neuroshareio.py
=> Make neuroshare robust for non-conform units

neo/rawio/baserawio.py
Fix proble when priting the number of channel and channel streams
=> Fix proble when priting the number of channel and channel streams

neo/io/nwbio.py
=> Add an error message suggesting to convert to a later NWB format

neo/rawio/openephysbinaryrawio.py
In the new OE version, `timestamps.npy` are already in seconds and do not need scaling by the sampling frequency (https://open-ephys.github.io/gui-docs/User-Manual/Recording-data/Binary-format.html#events)
In case the event stream has `states.npy`, the event channel type is an `epoch` since the duration can be computed using positive and negative states for each TTL channel.
=> Update Open Ephys events

neo/rawio/blackrockrawio.py
Fixes #1151 
(2nd try, hopefully this PR is cleaner)
=> BlackrockRawIO - Fix #1151 indexing bug when no nsx present

setup.py
=> Fix installation of "all" dependencies

neo/rawio/openephysbinaryrawio.py
=> [openephys] calculate durations only if state data exists

neo/core/dataobject.py, neo/core/epoch.py, neo/core/event.py, neo/core/spiketrain.py
=> Make rescale() signature compatible with quantities 0.14.0

neo/rawio/maxwellrawio.py
Fixing some typos and improving error message
=> Minor typos in Maxwell

neo/io/nwbio.py
also see
- https://github.com/NeurodataWithoutBorders/pynwb/issues/1300
- https://github.com/NeurodataWithoutBorders/pynwb/pull/1596
=> fix for #1227 (NWBIO bug)

codemeta.json
see https://codemeta.github.io
This is to help automate the registration of Neo in repositories of scientific software, e.g. EBRAINS.
In the future, I plan to automate updates to this file using GH Actions. Until that's done, it will need to be updated by hand for each release.
=> Add codemeta.json

neo/core/container.py, neo/core/group.py, neo/test/coretest/test_block.py, neo/test/coretest/test_segment.py
=> add `add()` function to `Container` for use on `Segment` and `Block`

.github/workflows/core-test.yml, neo/test/coretest/test_spiketrain.py
- drop NumPy 1.19, add 1.25 according to policy of "NEP 29 + 1 year"
=> Update NumPy versions we test with

neo/core/analogsignal.py
Fixes #1354
@samuelgarcia,
That is a real typo that needs to be fixed.
=> Fix typo in analogsignal repr

.github/workflows/publish-to-pypi-test.yml
=> Fix setting tag to env variable

neo/rawio/plexonrawio.py, pyproject.toml
* optimize imports
* add tqdm for longer steps
* add tqdm as a requirement for plexon
* a bit of black-like formatting
=> PlexonRawIO style

LICENSE.txt, README.rst, doc/old_stuffs/developers_guide.rst, doc/source/conf.py, doc/source/releases.rst, doc/source/releases/0.12.0.rst, doc/source/releases/0.13.0.rst, neo/test/README.txt
(plus some minor documentation tweaks).
=> Release notes for 0.13.0

neo/rawio/plexonrawio.py
=> PlexonRawIO

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/nlxheader.py
This branch includes the commit from @samuelgarcia to use numpy for a noticeable speed up of the section scanning.
=> Put back numpy approach for gap detections

neo/rawio/spikeglxrawio.py
=> Add 1016 to spikeglx

neo/rawio/intanrawio.py, neo/test/rawiotest/test_intanrawio.py
Propagate all the information extracted from header:
Here is a look at the properties through spikeitnerface new html repr (click on annotations and channel properties).
<div style='border:1px solid #ddd; padding:10px;'><strong>IntanRecordingExtractor: 192 channels - 20.0kHz - 1 segments - 71,172,603 samples - 3,558.63s (59.31 minutes) - int16 dtype - 25.45 GiB</strong></div><details style='margin-left: 10px;'>  <summary><strong>Channel IDs</strong></summary><ul>['A-000' 'A-001' 'A-002' 'A-003' 'A-004' 'A-005' 'A-006' 'A-007' 'A-008'
'A-009' 'A-010' 'A-011' 'A-012' 'A-013' 'A-014' 'A-015' 'A-016' 'A-017'
'A-018' 'A-019' 'A-020' 'A-021' 'A-022' 'A-023' 'A-024' 'A-025' 'A-026'
'A-027' 'A-028' 'A-029' 'A-030' 'A-031' 'B-000' 'B-001' 'B-002' 'B-003'
'B-004' 'B-005' 'B-006' 'B-007' 'B-008' …
=> Add annotations to intan

neo/rawio/plexon2rawio/plexon2rawio.py, neo/rawio/plexon2rawio/pypl2/pypl2lib.py
I was able to replicate issue #1349, and this appears to resolve it.
=> Patch for issue #1349 Issue with reading .pl2 files

neo/rawio/plexonrawio.py
=> Plexon overflow fix

neo/rawio/intanrawio.py
=> Make digital traces match memmap dtypes in neo.

neo/io/__init__.py
@alejoe91,
Needed for #1501.
This is the simple fix for your PR, but I want to run the full test suite to make sure it doesn't break something else which will require more complicated logic. But if this works you can review it then merge into main to get it for your PR. I've tested locally for a few of the new CatGT folders.
=> Add extra recursive step in `list_candidate_ios`

neo/rawio/spikeglxrawio.py, neo/test/rawiotest/test_spikeglxrawio.py
Fixes #1390
Added TCAT test files already present on GIN
=> Spikeglx: parse TCAT input

codemeta.json, doc/source/authors.rst, doc/source/releases.rst, doc/source/releases/0.13.2.rst, pyproject.toml
+ I switched over PRs to 0.13.2 if they qualified. I didn't do the same for issues....
=> Release Notes for `0.13.2` + author update + codemeta.json

neo/rawio/spikeglxrawio.py
Fixes https://github.com/SpikeInterface/spikeinterface/issues/3323
=> Fix spikeglx parsing bug

neo/rawio/biocamrawio.py
@h-mayorquin I was wrong, haha. We give a slice in spikeinterface which broke this :) 
@alejoe91, I don't have a biocam file easily available do you? I could test this, tonight with my personal laptop or we could merge and see what happens with full tests on SpikeInterface?
=> BiocamRawIO: Fix case where slice is given to `get_analogsignal_chunk`

neo/rawio/biocamrawio.py
=> Fix biocam dtype

doc/source/releases.rst, doc/source/releases/0.13.3.rst, pyproject.toml
@apdavison, you want to do a quick read of this?
=> Release notes 13.3

neo/rawio/blackrockrawio.py
=> Fix integer overflow in blackrock

neo/test/rawiotest/test_neuralynxrawio.py
Uses the existing NoDateHeader test data.
=> Add back in test of file using props_only option.

neo/rawio/neuronexusrawio.py
Follow up on this:
#3373
From this [comment](https://github.com/NeuralEnsemble/python-neo/pull/1509#discussion_r1777624427) I did not have enough time to address there
Just a more standard way of parsing datetime strings @zm711
=> Neuronexus datetime parsing

neo/rawio/maxwellrawio.py
=> Maxwell: skip streams without routing

pyproject.toml
See discussion here:
https://github.com/MEDFormat/MEDPython/issues/7
I discovered this while working on #1580, but I think it is better to get this into main here rather than in the release PR.
=> Limit dhn_med_py

neo/rawio/__init__.py
@alejoe91,
Realized I missed a tic for the documentation :)
=> NeuroNexusRawIO: Fix one doc typo

doc/source/authors.rst
As discussed we will add them to the codemeta.json when we do the next release (3 authors to add)
=> Add author

neo/io/biocamio.py, neo/rawio/biocamrawio.py
Just realised that I put wrong default value …
=> biocam io: fix minor default value for fill_gaps_strategy

doc/source/authors.rst
As always will add to codemeta.json right before release.
=> Add to author list

neo/rawio/spikeglxrawio.py
=> SpikeGLX: Adding NP1123 support

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
Providing an explicit test for Neuraview as well as further generalizing the date and time expressions. 
Built on generalizedHeaderProcessing and requires that reviewed first.
=> Neuraview test and refactor

.github/workflows/plexon2-testing.yml
Tested running plexon2 and noticed there was a bug with running it. I believe this should fix it.
=> Plexon2IO: tweak plexon2 action

neo/rawio/blackrockrawio.py
This is the second part of #1771 and should come after it. Check #1771 for a justification, the strategy is exactly the same.
=> Blackrock: improve nev data reading
