NeuralEnsemble/python-neo

.gitignore, neo/io/axonio.py, neo/io/blackrockio.py, neo/io/plexonio.py, neo/test/iotest/test_blackrockio_deprecated.py, neo/test/iotest/test_neuroshareio.py
(presumably ones which are skipped by Travis). Please could @maxgillett and @samuelgarcia take a look, as the failures were in `AxonIO` and `PlexonIO`.
=> Some attempted fixes for failing tests in the current master branch

neo/core/analogsignalarray.py, neo/test/coretest/test_analogsignalarray.py
Analogsignalarray.time_slice() does not require two quantities as input (t_start and t_stop), but also accepts None for any of them. If None is provided as t_start (t_stop) no shortening of the signal is performed at the beginning (end) of the signal.
=> time_slice of analogsignalarray also accepts None as t_start and t_stop values

neo/io/axonio.py
No matter whether lazy loading was requested or not, all of the data was
still read from the file. The lazy setting only affected whether the
data was put into the AnalogSignal object(s) or not.
=> Fix lazy loading for AxonIO

neo/core/analogsignalarray.py
Numpy warns that in version 1.9 all comparisons of the type "== None" are element-wise.  Since t_start and t_stop can be quantities arrays, they trigger this warning when they are compared to None using "==".  Since t_stop can be None, but can never be a quantity array with None (e.g. [None] * ms), element-wise comparison should never be needed so this change can eliminate the warning.
=> Changed "== None" to "is None" to avoid element-wise comparison warning.

neo/io/tdtio.py
I had some experimental collaborators who were saving all their data in a single TDT DataTank, so that `read_block`, the only read method for TdtIO, attempted to read > 100GB into memory. To get around this, I needed a method for reading individual segments. So in my fork I have
1. Implemented `TdtIO.read_segment`, which takes a `blockname` argument (block being the TDT block, the Neo segment) to specify which block. This was done by factoring the segment-reading code out of a for loop in read_block into its own function.
2. Made some formatting changes for better PEP8 compliance.
3. Used try/except blocks instead of conditionals when checking if a file exists. This is better practice (avoids a race condition).
The new code passes the TdtIO unit test.
Alternatively, I considered …
=> Implementation of read_segment for TdtIO

neo/core/segment.py, neo/test/coretest/test_segment.py
I recently discovered the absence of t_start and t_stop properties of segments. Since segments are meant to cover a specific time window, I think it could be useful to include the t_start and t_stop properties also for segments.
My implementation calculates t_start and  t_stop for a segment based on the earliest (latest) signal, which is linked to this segment. Probably there are more efficient implementations, but this could be a starting point.
=> t_stop and t_start property for segments

neo/io/blackrockio.py, neo/test/iotest/test_blackrockio.py
This pull request contains a fourth iteration of the BlackrockIO module to read files stored in the Blackrock file format.
The module is a combination from the previous two iterations combining the optimized, efficient, and more Neo compliant code of iteration 3 by @samuelgarcia with the important extended functionality of iteration 2. In addition, this IO adds several new features, in particular support for files of specification 2.1 and 2.3 and recording pauses (in 2.2 and 2.3). 
Also the code has been restructured to make it easier to add upcoming file specifications of Blackrock, by grouping read operations common to multiple file specifications (termed 'variants', e.g. 'variant_a').
Two new specific unit tests complement the generic IO unit tests and check the content of the read …
=> Added fourth iteration of BlackrockIO module with new features.

neo/io/blackrockio.py
Closes https://github.com/NeuralEnsemble/python-neo/issues/243
Was having some trouble using the BlackrockIO support working on Python 3.x. Fortunately, it ended up being pretty simple stuff. I went back and tested on Python 2.x to make sure it was still working.
Also, I had to tweak the `channel_labels` code as I was running into cases in our data where the channels IDs weren't grouped together.
Please let me know your thoughts on this and feel free to play with it.
cc @samuelgarcia (thanks for getting this to work with newer Blackrock versions 😄)
=> Fix BlackrockIO for python 3.x

neo/core/analogsignal.py
Minor fix by substituting "==" by "is" for comparison to None.
Using "== None" currently results in a warning: "FutureWarning: comparison to `None` will result in an elementwise object comparison in the future."
=> Updating check for NoneType by using "is" instead of "=="

neo/io/axonio.py
I set version to string to avoid floating point surprises.
I used int on division to avoid floating point division in py3 and get rid of deprecation warning with numpy reshape.
=> Small modification in io.axonio

neo/io/nixio.py, neo/test/iotest/test_nixio.py
This is a pull request to add an IO for [NIX](https://github.com/G-Node/nix). The IO uses the Python version of the library, [NIXPy](https://github.com/G-Node/nixpy) in pure Python mode (no compiled dependencies).
As of today, the version of NIXPy that is compatible with this IO should be on PyPI. The name of the package is `nixio` and the compatible version is `1.2.x`.
Note: NIX is a format based on HDF5 and uses the default file extension `.h5`. This may cause issues with file type detection if both the NIX IO and the HDF5 IO are used.
=> New IO for NIX

doc/source/authors.rst, neo/io/axonio.py
Decode `unit` byte array to string so that python3-quantities can deal with the unit and not fail when reading protocol waveforms from abf2 format files.
=> axonio: decode byte array to string when reading protocol units for python-quantities

neo/io/axonio.py
* len(range(dif)) == dif
* ana_sig[i_begin:i_end] has shape (X, 1), whereas np.ones() has (X)
resulting in: ValueError: could not broadcast input array from shape.
=> Simplify and fix array shape

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
Previously, testing was performed using an array of random numbers with length 0 (line 1161). Fixing the test also showed some bugs in the feature implementation, which are also fixed in this PR.
=> Fix tests and implementation of spiketrain 'duplicate with new data' feature

neo/io/nixio.py
Currently it transposes the list of elements, which leads to infinite processing by numpy. The first element of the list should be used instead, as is done in the surrounding code, since all the list elements are supposed to represent the same data.
The symptom is that that line causes cpu to get stuck at 100% and never stops.
=> Fix nixio infinite reading.

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
for shifting all spikes in a spiketrain by a constant amount of time. Currently, when adding a time quantity to a spike train, several properties like `t_start`, `t_stop`, and most importantly, `annotations` are lost.
Hope I am doing everything right here, first pull request. Apologies if something is off normal procedure.
=> reimplementing __add__ method for spiketrains

neo/core/analogsignal.py, neo/core/spiketrain.py
the default value "None" is now a dict "{}"
=> Issue166 In the __array_finalize__ method of AnalogSignal and SpikeTrain,

neo/test/generate_datasets.py
Fixes #281.
The call to `rand()` with anything other than an integer argument fails with an error in recent numpy versions. This PR converts `evt_size` to an integer before it is used.
=> Bug fix for Event data generation

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Some fixes and maintenance for the NIX IO:
- Remove support for C++ backend
The NIX IO was meant to rely on the pure Python backend of NIX. There was some code in the IO which made it compatible with the C++ backend before the Python backend was fully complete and polished, but now it's unnecessary and has been removed.
- Alias `nixio` import to `nix`
By convention, we `import nixio as nix`. This has the added benefit that it avoids any confusion that might arise from using the `nixio` package in the Neo-NIXIO.
- Remove dependency on `six`
It was used just for checking `string_types` so now the variable is set in the same way `six` sets it and the dependency is removed.
- Default file mode set to `rw`
Was read-only. Change is compatible with NIX and Neo tests.
=> NIX IO small fixes

neo/core/epoch.py, neo/core/event.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py
Implementing `time_slice` method for `Epoch` and `Event`
Issue #60
concerning the question I wrote in the thread of #60, it's now implemented that the individual epochs of an `Epoch` are only contained in the sliced `Epoch` if their start time falls within the slice time.
Hope it's done right this time ;)
=> Event epoch time slice

neo/io/axonio.py
Some values need to be converted to ints in order to work as indices
Some strings need to have .decode() called, not str(), or they have a spurious "b" at the start.
=> fix some python 3 incompatibilities in axonio

neo/core/analogsignal.py, neo/test/coretest/test_analogsignal.py
the access to "parents" property is only fixed for time_slice and copy, not yet for deepcopy
=> issue220 with tests

neo/io/axonio.py
This commit reads the field for sProtocolPath for ABF2. AxonIO already handles this field for ABF1 files and stores it in header['sProtocolPath'], so I followed the same convention.
=> Read sProtocolPath for ABF2 as well as ABF1

neo/io/neuroexplorerio.py
When parsing continuous signal from a NeuroExplorer file, the same byte offset was being used for indices, fragment starts, and data signal (i.e. `entity_header['offset']`). However, these are positioned sequentially in the file. This corrects the offsets such that the correct fragment starts, and signal are returned with the IO object. 
Tested against a local continuous signal file of `.nex` format.
=> NeuroExplorerIO: correct offset for continuous signal

neo/core/analogsignal.py, neo/core/epoch.py, neo/core/event.py, neo/core/irregularlysampledsignal.py, neo/core/spiketrain.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py, neo/test/coretest/test_irregularysampledsignal.py, neo/test/coretest/test_spiketrain.py
to simplify the common tasks of turning a Neo data object back into a plain Numpy array (many people do not know about `object.magnitude`) or into a Quantity array.
=> Add methods `as_array()` and `as_quantity()` to Neo data objects

setup.py
to clearly document the requirements for different io modules.
For example, this allows you to run:
```pip install neo[neomatlabio]```
and have the extra dependency needed for the `neomatlabio` module (scipy in this case) be automatically installed.
=> Added `extras_require` field to setup.py

neo/core/analogsignal.py, neo/core/channelindex.py, neo/test/coretest/test_analogsignal.py
Adds a `__getitem__()` method to `ChannelIndex` and ensures the `channel_index` attribute of an `AnalogSignal` is updated when extracting a subset of channels from it.
=> Fix for #320

neo/io/__init__.py, neo/io/neuralynxio.py
This PR fixes
1. An incorrect link within the generated neo structure
2. A missing autoclass entry for the NeuralynxIO
=> Minor fixes for NeuralynxIO

neo/core/spiketrain.py
This PR solves two bugs in the current implementation of `SpikeTrain.duplicate_with_new_data `
1. Waveforms provided are not considered for the duplicated spiketrain as they are automatically overwritten by the  old version of the waveforms. Same holds true for t_start and t_stop.
2. The time consistency check is not considering the quantity unit of the provided t_start and t_stop, which leads to wrong results in the time consistency check.
Both bugs can be observed in the following code snippet
```
st = neo.SpikeTrain(np.arange(5,15)*pq.s, t_start=0*pq.s,t_stop=20*pq.s, sampling_rate=1*pq.Hz)
wfs = np.arange(100).reshape((10,1,10))*pq.V
st.waveforms = wfs
new_st = st.duplicate_with_new_data(st.times[:5], st.t_start, st.t_stop, waveforms=st.waveforms[:5])
new_st = …
```
=> Fix waveform and time handling when duplicating spiketrains

neo/io/blackrockio.py, neo/test/iotest/test_blackrockio.py
This PR includes a package of several fixes to the revised blackrockio that is available since Neo 0.5, which were contributed by various people. In particular, this PR fixes:
* New parameter `scaling` to indicate whether analog signals are scaled to mV ('voltage'), or left as raw integer values ('raw'). Note that the default was set to "raw", since for file spec 2.1 and below, only in the presence of a `nev` file the conversion to voltage can be done. However, note that this may lead to different behavior since the initial inclusion of the new blackrockio. Changing the default to `voltage` is of course discussable.
* Fixed issue where one unit test was not actually testing correctly
* Fix issue where available channels were pooled only from nsX files, not the nev.
* Fixed issue where …
=> Cumulative set of fixes for blackrockio

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Implements the naming scheme discussed in #311 for the NixIO:
1. When a Neo object is written to NIX, a unique `nix_name` is generated.
2. The NIX name is added to the Neo object as an annotation (`nix_name`).
3. The Neo object's original name is stored in the NIX object's metadata (`neo_name`).
4. When reading the file, the Neo object's original name is restored and the autogenerated NIX name is stored as an annotation.
During step 1., if the Neo object already has a `nix_name` annotation, that name is used instead of generating a new one.
Other changes:
- Updated tests to comply with new naming scheme.
- Maintains a path->object map for efficiently accessing the same object multiple times during a session based on the internal path representation.
- For every NIX object created, the …
=> [NixIO] New object naming scheme

neo/io/baseio.py
Change name of attribute from extentions to extensions.
=> [baseio.py] Correct a typo in name of attribute

README.rst
On pypi this is borken: python setup.py upload_docs
The doc at pythonhosted was a very old one. (0.3.3).
So I have manually remove the old doc
Now http://packages.python.org/neo/ do not exist anymore.
=> New URL for documentation.

neo/io/blackrockio.py
This PR fixes a small bug in BlackrockIO, where the filter settings of the spike wave form extraction had units of uV instead of Hz. Also, this PR adds new annotations to the Channelindex that indicates the filters of the nsX file [x in 1..5], if present. The ns6 file, that may exist in addition to one ns1-ns5 file, has no filters.
=> Fixed a bug in BlackrockIO ChannelIndex annotations, and adds a few new ones.

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
In the current SpikeTrain implementation the attributes and annotations of a SpikeTrain are only shallow copied when duplicating the SpikeTrain. With this PR the attributes and annotations of a SpikeTrain can be copied using the 'deep_copy' keyword of the duplicate_with_new_data function.
=> Add deep_copy option for spiketrain duplication

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
In Python 2.7, waveforms are sliced twice when slicing a spiketrain. This is due to the double implementation of the waveform slicing in` spiketrain.__getslice__ `and `spiketrain.__getitem__`. However both implementations are necessary, since only `spiketrain.__getslice__` is used for Python 2.6 and only `spiketrain.__getitem__` for recent Python versions.
I don't know why the corresponding tests didn't fail for Travis, but they failed locally on my machine.
=> Fix duplicate waveform slicing

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Currently, the NixIO does not properly handle cases where the same Neo object is attached to multiple locations. For instance, if an AnalogSignal is attached to multiple Segments, the NixIO will fail on write while attempting to create the same object a second time.
With this PR the IO now detects such cases and mirrors the references between Neo objects as closely as possible in the NIX file (e.g., the DataArray created from the AnalogSignal in the above example will be attached to multiple Groups).
An IO test has been added for this behaviour (`test_multiref_write`).
The issue was first described in https://github.com/NeuralEnsemble/python-neo/issues/311#issuecomment-307563228. Since the new naming scheme was already merged and the problem mentioned in the issue is fixed, this PR closes …
=> [NixIO] Proper handling of multiple references to the same object

neo/core/analogsignal.py, neo/core/container.py, neo/core/irregularlysampledsignal.py, neo/core/spiketrain.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_irregularysampledsignal.py, neo/test/coretest/test_spiketrain.py
for `AnalogSignal`, `IrregularlySampledSignal`, `SpikeTrain`. Also fixed `IrregularlySampledSignal.copy()`
Fixes #353
=> Preserve parent objects on `rescale()`

neo/core/analogsignal.py, neo/test/coretest/test_analogsignal.py
The former gives the array index corresponding to a given time, the latter replaces part of a signal with another (generally smaller) signal. It is intended to be used for removing transients and other artefacts.
=> Add `time_index()` and `splice()` methods to `AnalogSignal`

neo/rawio/blackrockrawio.py
The channel_id and unit_id values were determined in a for loop and saved to a list. When reading them to set the annotations the temporary variables that contain only the last values were read. Now the values are read from the list as originally intended.
=> Fixed channel_id in Unit annotations always 144 and unit_id always 1 in BlackrockIO

neo/rawio/blackrockrawio.py
I promise I'm not combing through the code looking for tiny bugs. I'm writing a new io and I'm using the existing rawio's as examples. Sometimes I find something that I think might be a bug but it may just as well be there on purpose because of some weird idiosyncrasy of the data format. This is one of those times. I think it's a bug but I could easily be wrong.
PR passes test_blackrockio in intel python3.5 on Ubuntu 16.04
=> blackrockrawio _get_event_timestamps make use of t_start, t_stop

neo/rawio/blackrockrawio.py
I fixed a bug (see #420) that caused BlackRockIO to fail loading certain files because of spikes otuside of the time range set by the nsX start and stop times. Now _segment_t_start in BlackrockRawIO returns the smaller of t_start (read from available nsX files) and the first spike timestamp instead of t_start. Also the general t_stop is now set to the higher of t_stop from nsX and the last spike timestamp, thus  _segment_t_stop now returns this.
Apart from that I changed the value of self._t_starts in BlackrockRawIO from 0 to the first spike timestamp if no nsX file is available.
=> Fixed bug with BlackrockIO not loading because of spike times before/after t_start/t_stop

neo/rawio/blackrockrawio.py
The latest version of BlackrockIO using the RawIO API was missing a few annotations for the Block objects that contained information on available files and recording pauses. Using the already existing structure for annotations in RawIO I added the checks for those annotations like it was done in earlier versions of BlackrockIO.
=> Added back list of available files as annotations to block in BlackRockRawIO

neo/core/analogsignal.py
Ironically, this seems to have been spliced in during a merge
=> Remove mutated copy of `AnalogSignal.splice()`

neo/rawio/blackrockrawio.py
After playing around a lot with the new BlackrockRawIO I was able to get Blackrock files of version 2.1 to load (see also issue 417). I copied some parts of the old IO over because they were referenced but not yet available and adapted them to fit into the new structure. They originally required more data being available already but this could be eliminated because the needed functionality (a lot less than the original methods had) did not require those. Using this code I was able to fully load files of version 2.1.
=> Fix for loading Blackrock files of version 2.1

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
Issue #412 states that SpikeTrain.times should return a Quantity instead of a SpikeTrain. This pull request should fix this behavior. This makes obj.times more consistent across all neo objects, as SpikeTrain was the only one with this behavior.
I also adapted the docstrings and UnitTests accordingly.
However, I'm wondering if there was a reason for having it return a SpikeTrain, because this was tested quite often in the UnitTests and also the documentation explicitly states that a SpikeTrain should be returned.
=> Made SpikeTrain.times return Quantity instead of SpikeTrain

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py, neo/test/iotest/test_nestio.py
=> Raise a `ValueError` if `t_stop` is earlier than `t_start` when creating an empty `SpikeTrain`

neo/core/epoch.py, neo/test/coretest/test_epoch.py
so that durations and labels are correctly sliced. Fixes #413
=> Implement `__getitem__` for Epoch

neo/rawio/blackrockrawio.py
This fixes that connector_ID and connector_pinID could only be read from a nev file although the information is present in the same way in nsX files.
Apart from that it now checks for nsx_spec when reading information from nsX instead of checking nev_spec, which might be a problem when no nev files are present.
=> BlackrockRawIO: Enabled reading connector_ID and connector_pinID from

neo/core/container.py, neo/test/coretest/test_block.py, neo/test/coretest/test_channelindex.py, neo/test/coretest/test_segment.py, neo/test/coretest/test_unit.py
Closes issue #493
This allows to filter for objects of a specific type without specifying another filter attribute.
Previously filters like ```targdict={}, object=neo.SpikeTrain``` returned an empty list, where as now this returns all SpikeTrain objects available.
=> [MRG] Change filter behaviour to return all objects if no filter parameters are specified

neo/io/basefromrawio.py
Last minut proposal for 0.6: add channel_names and channel_ids in AnalogSignal when channel are grouped.
For beginner it is easier to have directly channel_names in AnalogSignal than in ChannelIndexes.
Example:
```python
reader = neo.MicromedIO(filename='myfilen.trc')
seg = reader.read_segment()
anasig = seg.analogsignals[0] # this have all channels
print(anasig.annotations['channel_names']) # this print all channels
```
This behavior will be superseded by array_annotaiont but it is cool to have then in 0.6.
=> Proposal: add channel_names/ids in AnalogSignal when channel are grouped

neo/core/epoch.py, neo/core/event.py, neo/core/spiketrain.py
This PR fixes the unittests failing due to the ipython version 6.3.1 (#518).
The problem was that event, epoch and spiketrain objects were inheriting the _repr_pretty_ method from baseneo, but this is not used in the new ipython version, since it is not listed in the __dict__. A quick solution is to explicitely have the _repr_pretty_ being listed in the neo.Event.__dict__ by implementing it in the corresponding classes.
I am not sure if this is the best way to solve this issue, as it introduces changes in 3 classes, even though the problem seems to be a central one. I would be happy about alternative ideas to solve the issue.
=> [MRG] Add explicit _repr_pretty_ for events, epochs and spiketrains.

neo/rawio/tests/tools.py, neo/test/iotest/common_io_test.py
In the current state (in Python3, Python2 see below) when a file that is required for testing is unvailable on gin (e.g. Error 404), the unittest will just be skipped. This means, in case only a single file required for one test class is not available, the whole class of tests will just be skipped. Consequently, if there was a failure on gin, all IO tests (and any other tests requiring data from gin) would just be skipped. So CircleCI would just mark every pull request that only makes changes to IO as correct (Skipped tests mean the overall test is passed). This could even go unnoticed for quite a while, so it's probably better to make tests fail and explicitly state that something is wrong about the data. This is done in this pull request.
Apart from that, in Python 2.7 when a file was …
=> Make Unittests fail if the required data are unavailable

neo/io/nixio.py
After installing Neo 0.6.1, I tried to load a Nix file using Neo with the following lines:
```py
neo_file = NixIO(filename, "ro")
block = neo_file.read()
```
which prompted the following error:
```
Traceback (most recent call last):
File "C:/Users/CPL/PycharmProjects/ephys_analysis/ephys_analysis/free_playground.py", line 85, in <module>
raw_signal = get_electrode_data(h5_filename, LFP_electrode_name)
File "C:\Users\CPL\PycharmProjects\ephys_analysis\ephys_analysis\elephant_main.py", line 21, in get_electrode_data
block = neo_file.read()
File "C:\python_venv\lib\site-packages\neo\io\baseio.py", line 116, in read
return self.read_all_blocks(lazy=lazy, **kargs)
TypeError: read_all_blocks() got an unexpected keyword argument 'lazy'
```
I fixed this error by adding the lazy keyword to the …
=> nixio doesn't support lazy loading.

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Sorting creates issues with lexicographical ordering of numbers.
This PR removes all name-based sorting of DataArrays (signals) and lets the HDF5 creation order tracking take care of the signal order.
=> NIXIO data ordering fix

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Fix for #548. The `file_datetime` wasn't being converted along with other datetime objects during write. Included instances of `file_datetime` on Block and Segment in test.
=> [nixio] Convert file_datetime to int when writing

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Last year I changed the NixIO to use UUIDs as names for objects as a way to get around a couple of issues. Issue #311 is where the discussion happened and #331 is the relevant PR where this was implemented.
Some time later, there was a [discussion on the mailing list](https://groups.google.com/d/topic/neuralensemble/u0m79CbibA0/discussion) regarding the write performance but, as a side topic, the issue of the naming also came up. In short, with the current naming scheme, the NIX/HDF5 file that is generated has names that make it difficult to work with and can be a hindrance (and an annoyance) for people who purposefully name their objects in order to be able to navigate a file.
This PR adds a new feature which somewhat backtracks from the design decision of automatically naming objects. …
=> [nixio] Use Neo object names in NIX file

neo/io/blackrockio.py, neo/test/iotest/test_blackrockio.py
This PR tackles #419 by allowing to specify nsx_to_load='all' when initialising the BlackrockIO. The implementation is probably not the most elegant one, but it comes with a test covering the new feature.
=> BlackrockIO loading of multiple blackrock nsx files

neo/io/nixio.py, neo/test/iotest/test_nixio.py
The `nix_name` annotation was mistakenly used to determine if an object had already been written. This PR fixes the writer to check the actual contents of the file or the `_signal_map`, a dictionary it keeps to be able to reference groups of signal objects by name that's created during the writing of a Block.
The issue arises when an object has been annotated by a previous write or from being read from a different file, which was the underlying cause of issue #535.
=> Nixio object rewrite

neo/core/analogsignal.py, neo/core/irregularlysampledsignal.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_analogsignalarray.py, neo/test/coretest/test_irregularysampledsignal.py
This PR is based on #557. In addition to #557 it implements indexing of AnalogSignals and IrregularlySampledSignals via numpy arrays. The returned object is a quantity object, as the temporal information can not necessarily be captured by an AnalogSignal or IrregularlySampledSignal.
See also #556 for the discussion.
=> Indexing of AnalogSignals and IrregularlySampledSignals using numpy arrays

neo/test/iotest/test_blackrockio.py, neo/test/iotest/test_brainwaredamio.py, neo/test/iotest/test_brainwaref32io.py, neo/test/iotest/test_brainwaresrcio.py
See #568 
Now the position of the warning in the list of warnings is not assumed anymore. 
Instead the test checks if the warning is in the list of warnings.
Apart from that the warnings.simplefilter filter should only be changed within
the context of catch_warnings here in order to ensure it being set to its original
state afterwards. Alternatively it needs to be reset manually. This was done as well.
=> Fixed detection of warnings in test_blackrockio.py (#568)

neo/rawio/blackrockrawio.py
With this PR the user only receives a warning in case there is an event code
that's not known to BlackrockRawIO instead of raising an Error which
would at least cause some valid data not to be loaded.
=> [BlackrockIO] Warn user in case of unknown event code

neo/rawio/neuralynxrawio.py
in header there is a key:
```
-InputInverted False
```
which is interpreted as True when you use `bool('False')`
=> fix bug for bool key type in neuralynxrawio.py

.circleci/requirements_testing.txt, doc/source/authors.rst, neo/io/__init__.py, neo/io/axographio.py, neo/test/iotest/test_axographio.py, setup.py
This PR proposes an IO class for reading from AXGX and AXGD files using [`axographio`](https://github.com/CWRUChielLab/axographio). It provides an alternative to `StimfitIO` for importing axograph files which may be a bit easier to get up and running, particularly on Windows.
=> Implement AxographIO module with tests

neo/io/__init__.py, neo/io/nixio_fr.py, neo/rawio/__init__.py, neo/rawio/nixrawio.py, neo/rawio/tests/test_nixrawio.py
This PR adds the NIXRawIO file and the test for it.
The raw reader assumes that all blocks have the same object tree, since the docstring for baserawio.py says 
>neo tree object is symetric and logical: same channel/units/event along all block and segments.
I noticed that there aren't any other rawios which support multiple blocks and we want to support multiple blocks in NIXRawIO. I think we can add support for asymmetrical blocks but this would require changes in the baserawio (as far as I can tell). Would this be useful or it is redundant for the rawios?
=> New RawIO for NIX files

neo/rawio/axonrawio.py
This change corrects the issue raised in https://github.com/NeuralEnsemble/python-neo/issues/544
=> support for unexpected nTelegraphEnable values

neo/rawio/neuralynxrawio.py
Guys, I've made an update for a workaround with the empty nse files
There still will be info in self._spike_memmap, but it will be just empty numpy arrays
=> account for empty nse in rawio.neuralynxrawio

neo/rawio/blackrockrawio.py
This is a rebase of #570.
I also changed __get_nonneural_evtypes_variant_b to match @cboulay  's implementation which is cleaner and in line with the Blackrock manual.
=>  Blackrock - separate dig input and serial input

neo/rawio/axonrawio.py
Noticed that there was an EpochInfoDescription block sitting around that wasn't being used, so I followed the format of the other sections to parse an 'EpochInfo' block into the ABF2 header. On initial inspection, it seems to work properly and I can see the digital output epochs.
A caveat is that each DAC channel can define it's own epoch durations and the EpochInfo returned doesn't provide a duration field. So for example, if Epoch A is defined as 1 second in CMD#0 and as 5 seconds in CMD#1, it isn't necessarily obvious which length the digital output pulse should be if you were to turn the EpochInfo section into a waveform. (Similar to how read_raw_protocol converts the dictEpochInfoPerDAC into a waveform). Still, I think that parsing the EpochInfo block is useful.
=> Parse EpochSection in ABF2 files to get digital output waveform info

neo/io/__init__.py, neo/io/rawmcsio.py, neo/rawio/__init__.py, neo/rawio/rawmcsrawio.py, neo/rawio/tests/test_rawmcsrawio.py, neo/test/iotest/test_rawmcsio.py
Need to add some files at gin for testing.
But ready to be reviewed.
=> [MRG] Implementation of the "raw" Multi Channel System (MCS) IO

.circleci/requirements_testing.txt, doc/source/install.rst, neo/io/nixio.py, neo/rawio/tests/test_nixrawio.py, neo/test/iotest/test_nixio.py, setup.py
The NIX library is being updated to v1.5. This brings changes to the metadata format and the IO needs to be updated to work with the new version.
List of changes in this PR:
- New metadata handling: Property values are no longer of the type nix.Value. Values are simply created and returned as native Python types.
- HDF5 backend option removed from Python nixpy library (only h5py supported now), so the selection argument is removed.
- The neo-nixio loads metadata from linked nix.Sections into a Neo object's annotations now. NIX metadata sections can be linked to other sections and *inherit* their properties. If a user does this kind of linking in the NIX file, the linked metadata properties are loaded along with the metadata properties of the primary data object's metadata section.
- …
=> [nixio] New library version 1.5

neo/core/epoch.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_irregularysampledsignal.py
My env:
```
$ conda list
#
alabaster                 0.7.6                    py27_0    http://repo.continuum.io/pkgs/free/osx-64/alabaster-0.7.6-py27_0.tar.bz2
allensdk                  0.12.0                    <pip>
babel                     2.1.1                    py27_0    http://repo.continuum.io/pkgs/free/osx-64/babel-2.1.1-py27_0.tar.bz2
certifi                   2016.2.28                py27_0    defaults
chardet                   3.0.4                     <pip>
coverage                  3.7.1                    py27_0    http://repo.continuum.io/pkgs/free/osx-64/coverage-3.7.1-py27_0.tar.bz2
cython                    0.27                      <pip>
dateutil                  2.1                      py27_2    <unknown>
docutils                  0.12                     py27_0 …
```
=> Fix some bugs which I see on my laptop, although apparently they are not caught by Travis or CircleCI?

neo/io/blackrockio_v4.py, neo/io/elphyio.py, neo/io/neomatlabio.py, neo/io/neuralynxio_v1.py, neo/rawio/brainvisionrawio.py, neo/rawio/elanrawio.py, neo/rawio/neuralynxrawio.py, neo/rawio/neuroexplorerrawio.py, neo/rawio/plexonrawio.py, neo/rawio/spike2rawio.py
Fix warnings see #602
* fromstring warnings
* DeprecationWarning: invalid escape sequence
=> Fix warnigs before 0.7

neo/io/nixio.py, neo/test/iotest/test_nixio.py
There was a bug in read_block() when multiple calls both with and
without arguments. The automatic indexing was buggy and would increment
even when it didn't have to.
Test added to catch regressions.
=> [nixio] Fix in read_block() auto indexing

neo/io/nixio.py, neo/test/iotest/test_nixio.py
In older versions of Python (< 3.6) the builtin dict isn't ordered, so
signal grouping during read can get randomised.
Switch to using OrderedDict to support older versions as well.
=> [nixio] Use OrderedDict to group signals

neo/io/neuroshareapiio.py, neo/io/neurosharectypesio.py
These IOs still contained outdated references to event- and epocharrays.
=> Update neuroshareios to neo 0.6

neo/rawio/nixrawio.py, neo/test/iotest/test_nixio_fr.py
in Reference to Issue #575 , some basic test for nixio_fr and compatability test of nixio and nixio_fr is added.
=> create basic and compatability test for nixio_fr

.travis.yml
as we don't test the `io` modules there.
Now Coveralls gets coverage information only from CircleCI
cf #506
=> Stop pushing coverage information to Coveralls from Travis CI

neo/core/dataobject.py
See #621 
I propose to make a release with version 0.7.1 as soon as this is merged, so that we can reduce the impact of updating Neo on downstream projects. What do you think @samuelgarcia ?
=> Add an alias for `duplicate_with_new_data`, for backwards compatibility.

doc/source/core.rst
The URL for test files changed at some point but the docs did not reflect that in the example for AxonIO.  That example fails with the old URL and works with the new one.
=> Update docs to reflect correct URL for test files

.circleci/config.yml, neo/io/asciisignalio.py, neo/rawio/examplerawio.py, neo/test/iotest/test_asciisignalio.py
in preparation for working on #579. Main changes:
(1) moved most arguments from `read_segment()` method to the IO class constructor, and added a `read_block()` method. This makes AsciiSignalIO more consistent with other Neo IOs.
(2) added an argument "multichannel", to control whether to create a multi-channel AnalogSignal or a list of single-channel signals. The default is the latter, for backwards compatibility.
(3) more consistency checks on argument values
(4) fixed a bug with "genfromtxt" where usecols would be applied twice.
=> Some improvements to AsciiSignalIO

neo/rawio/blackrockrawio.py
The thresholds are applied to the digitised signal in the Blackrock software, to use them with the converted analog signal we need to multiply them by the digitisation factor.
=> BlackrockRawIO: Fixed thresholds not being multiplied by the digitisation factor

neo/io/asciisignalio.py, neo/test/iotest/test_asciisignalio.py
(cf #649)
Not implemented: write support for IrregularlySampledSignals
=> Add support for reading IrregularlySampledSignals in AsciiSignalIO

neo/core/container.py, neo/test/coretest/test_container.py
Raise a meaningful error if `filter()` is called with a single string rather than dict/kwargs
Fixes #661
=> Fix for #661

neo/core/epoch.py, neo/core/event.py, neo/io/brainwaresrcio.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py, neo/test/test_utils.py, neo/utils.py
I failed to notice during the review of #606 and #472 that the implementation of `Event.labels`, `Epoch.labels` and `Epoch.durations` had been changed to store these attributes as array annotations.
I think this change is a mistake, because (i) semantically labels and durations are not annotations, they are fundamental data attributes for these objects, so it is confusing to handle them as annotations; (ii) annotations are treated differently to data attributes during copying and merging, and this can lead to problems.
I encountered this specifically while trying to fix problems with the `Container.merge()` method; I suspect it is also related to https://github.com/NeuralEnsemble/elephant/pull/203
=> Revert implementation of Epoch and Event to not use array annotations machinery for label and duration

neo/rawio/brainvisionrawio.py
This patch allows importing VHDR files in which the per-channel metadata (under "Channel Infos") uses lowercase field names (e.g., `ch1=...` instead of `Ch1=...`). That affects files from at least [one](https://www.cognionics.net/) vendor. 
A sample file that reproduces the issue is [here](https://github.com/NeuralEnsemble/python-neo/files/3234417/cog-test.zip). Note that this file also happens to trigger an unrelated bug later into the import (related to no channel coordinates being present, which is quite common), which is not fixed by this PR, but you can verify that with the fix it will make it further through the file than without.
=> Fix crash with some VHDR files that spell channel records in lowercase

neo/rawio/brainvisionrawio.py
Currently the BrainVision importer will crash when a file is missing the `[Coordinates]` section, which appears to be quite common (we have many of those). [Here](https://github.com/NeuralEnsemble/python-neo/files/3234457/cog-test2.zip) is a small sample file that exhibits this issue (note I hand-edited the file so that it doesn't also trigger an unrelated problem, which is fixed by a [separate](https://github.com/NeuralEnsemble/python-neo/pull/673) PR).
=> Fix import crash with VHDR files that have no channel coordinates

doc/source/authors.rst, neo/rawio/neuralynxrawio.py, neo/test/iotest/test_neuralynxio.py
@samuelgarcia 
As we discussed in #591, I've switched to tuples in memmaps, because channel IDs are not unique for the acquisition, but the channel names are. The thing is that NLX allows to set different preprocessing parameters for each channel ID and create new files, e.g. one file contains highpassed data for spikes, second - true DC recording, third - common channel with LFP 0.1Hz-100Hz, etc. And they all could be collected from the same channel ID!
Note, CSC1 and CSC33 have the same ID, but different gains (also different highpass parameters)
An example of simultaneous recording of DC and AC from the same channel ID
Now, memmaps and dicts have the following structure:
=> switch to tuples in chan_id in neuralynxrawio.py

neo/io/proxyobjects.py
I was wondering what people think about adding a `time_slice` method to all proxy objects?
They already have `load(time_slice=(t_start, t_stop), ...)`, but this call signature differs from the `time_slice(t_start, t_stop)` call signature used by non-proxy objects. It would be nice to have identical call signatures for both proxy and non-proxy objects so that code that uses them can be agnostic about whether the object has already be loaded into memory or not.
For example,
```python
import neo
io = neo.io.get_io(filename)
blk = io.read_block(lazy=True)  # or lazy=False
sig = blk.segments[0].analogsignals[0]
sig.time_slice(0*pq.s, 5*pq.s)
```
could just work for both `lazy = True` and `lazy = False`.
This pull request implements the simplest solution I could think of, which is basically to …
=> Suggestion: Add time_slice method to all proxy objects

neo/io/nixio.py
Small modification of the naming scheme described in PR #331:
In step 4, upon reading the 'neo_name' property and restoring the original Neo object's name, the 'neo_name' attribute is now discarded.  Since we already restore this to the name of the object, there's no need to keep it around in the object's annotations.  More importantly, it would create a conflict on rewrite of an object, since the creation of the property is handled explicitly, outside of the general annotation conversion function.
Fixes #694
=> [nixio] Discard 'neo_name' property on read

neo/test/generate_datasets.py
The default `sampling_rate` has units kHz, and the default `duration` has units s. By dropping units from their product without first simplifying, the number of data points was off by a factor of 1000. Consequently, the default 6 second signal was instead 6 milliseconds long.
=> Fix for duration of signals in `generate_one_simple_segment`

neo/core/analogsignal.py, neo/core/epoch.py, neo/core/event.py, neo/core/irregularlysampledsignal.py, neo/core/segment.py, neo/core/spiketrain.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py, neo/test/coretest/test_irregularysampledsignal.py, neo/test/coretest/test_segment.py, neo/test/coretest/test_spiketrain.py, neo/test/test_utils.py, neo/utils.py
As suggested by @apdavison in #657 I turned utility functions that operate on single objects into methods of the respective classes. Time-shifting and -slicing deep-copies the object and thus destroys links to parents as discussed in #668 .
I circumnavigated import-cycles by identifying proxy-objects by their `_rawio` attribute instead of an explicit `isinstance`. I'm open to suggestions on how to do this more elegantly.
While adding `IrregularlySampledSignals` to `Segment.time_slice` I noticed that there is no proxy-object for them. The code should still work if and when they are added.
=> Turn time-slicing and -shifting utilities into methods of the corresponding classes

neo/io/nixio.py, neo/test/iotest/test_nixio.py
This PR adds support 1-dimensional ChannelIndex coordinates.  1D coordinates in ChannelIndex can occur when there is only one channel and the coordinates are specified as a vector (see issue #666).  When 1D coordinates are found they are wrapped in a list and treated the same as the general case.
=> [nixio] Support 1D coordinates for single ChannelIndex

neo/core/baseneo.py, neo/core/container.py, neo/test/coretest/test_channelindex.py, neo/test/coretest/test_segment.py, neo/test/coretest/test_unit.py, neo/test/tools.py
When merging two container objects, the children merged from the other container into the target container should have the appropriate parent attribute set to reference the target.
Example:
After `seg1.merge(seg2)`, we expect that all the AnalogSignal objects in `seg1.analogsignals` should have `sig.segment == seg1`, whether `sig` was originally in `seg1.analogsignals` or `seg2.analogsignals`.
After the operation, `seg2` will be in an inconsistent state, but I think this is ok, as I wouldn't normally expect to continue using an object after merging it into another. The alternative is to take a copy of `seg2` before merging it, but this would likely have a bad effect on the performance of `merge()` for little benefit.
=> Fix merge behaviour

neo/io/nixio.py, neo/test/iotest/test_nixio.py
The NixIO currently just ignores array annotations. I went through it with @achilleas-k and added them analogously to annotations. For writing this is straightforward, when reading I check the shape of all annotations and turn them into array annotations if it matches.
=> Fix Nix Ignoring Array Annotations

neo/io/nixio.py, neo/test/iotest/test_nixio.py
This PR add enables the NixIO to write ProxyObjects by loading them on request and adds a test for this.
=> Write Proxyobjects with NixIO

neo/rawio/nixrawio.py
See the same fix in NIXio for details in PR #695
Fix #694
=> [nixrawio] Discard neo_name property on read

doc/source/io_developers_guide.rst, doc/source/rawio.rst, neo/io/__init__.py, neo/rawio/__init__.py, neo/rawio/blackrockrawio.py, neo/rawio/openephysrawio.py
The [Neo IO doc page](https://neo.readthedocs.io/en/latest/io.html#module-neo.io) has a list of implemented formats, but the [Neo RawIO doc page](https://neo.readthedocs.io/en/latest/rawio.html) does not. This PR fixes that, as well as some doc build warnings.
Think we can fit this in before the release?
=> Add list of implemented RawIO classes to docs

neo/core/epoch.py, neo/core/event.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py
* all can be created with lists (provided the units parameter is provided), not just with arrays
* `obj.__getitem__` with a scalar argument returns a Quantity
* `obj.__getitem__` with a slice or array argument returns an object of the same type
cf #490
=> Improve consistency between Epoch, Event and SpikeTrain

neo/io/nixio_fr.py, neo/rawio/nixrawio.py, neo/test/iotest/test_nixio.py
This PR fixes the bug that was introduced in #629 that required disabling the lazy load test (see #721).  The test is now enabled again.
The basefromrawio class creates ChannelIndex objects and appends annotation values to existing annotations, one for each signal in the channel.  This creates an issue with the `nix_name` annotation which is meant to be used as the NIX object name when the Neo structure is written to a NIX file.  We override the `read_block()` method from the `BaseFromRaw` class to first call the original method and then trim the `nix_name` annotation to make it a single value rather than a list.
https://github.com/NeuralEnsemble/python-neo/blob/5fae976d1d944bf16285dc51f57d0e7d4c2c62ad/neo/test/iotest/test_nixio.py#L1385
The lazy load test (linked above) performs the …
=> [NIXIO] Trim nix_name annotation for chx objects

neo/io/nixio.py, neo/rawio/nixrawio.py
This PR adds a version compatibility check function to the NIX IO.
Currently the IO requires NIXPy (nixio) version 1.5 or greater (betas included). The version checker only checks the first two components of the version string.
The same function is used in the constructor of the NIXRawIO.
Some codestyle cleanup for the NIXRawIO is included.
=> [NIXIO] version checks

neo/io/nixio.py, neo/test/iotest/common_io_test.py, neo/test/iotest/test_nixio.py
Handling Issue #748 
The issue arises from this part of the loading routine which adds properties which are an array_annotation to a corresponding nested dict within _neo_attrs_, but also adds them as a regular annotation, therefore creating a duplicate.
nixio.py line 1237-1244 (in method __nix_attr_to_neo_):
```
elif prop.definition == ARRAYANNOTATION:
if 'array_annotations' in neo_attrs:
neo_attrs['array_annotations'][prop.name] = values
else:
neo_attrs['array_annotations'] = {prop.name: values}
else:
values = list(values)
neo_attrs[prop.name] = values
```
It seems that PR #662 intended not to duplicate the array_annotations, but the duplication was then introduced with the merge commit 0a4ccfae4aca7d854d3f1065bd8782136981f1ab
Please comment @Kleinjohann ?
The PR separates the …
=> [Update to PR #662] fix duplication of array_annotations into annotations

neo/core/spiketrain.py, neo/test/coretest/test_spiketrain.py
This fixes #763 
An additional simplified statement makes sure that CompoundUnits are first simplified such that the "true" unit can be reliably extracted. Additional, a regression test based on #763 is implemented, which failed on the pervious build.
=> Fix for SpikeTrain consistency check encountering CompundUnits

neo/io/nixio.py
Runs the two utility methods before returning loaded Neo Blocks.
See #766.
=> [nixio] Create many to one and many to many relationships

neo/io/nixio.py, neo/test/iotest/test_nixio.py
This PR adds support for saving and loading date, time, and datetime objects to NIX without losing the original data type.
On write, it marks annotations by setting property.definition to DATE, TIME, or DATETIME.  On load, it uses the definition to recreate the original object.
Fixes #783.
=> [NIXIO] Save and load date, time, and datetime annotations

neo/core/analogsignal.py, neo/core/irregularlysampledsignal.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_irregularysampledsignal.py
In the context of #526 it might be useful to add utility functions for adjusting the time sampling of `AnalogSignals` and `IrregularlySampledSignals`. This PR is wrapping the two scipy functions `decimate` and `resample` to provide a mechanism for decimating and resampling within Neo and adds some tests with it.
There is one issue coming with this PR: Scipy itself is not a Neo dependency yet, even though it is used in a couple of places for specific IOs. Here, I the new utility methods can only be used in case of scipy being available and will raise an ImportError if this is not the case.
Note: As scipy is not available in the Travis test setup, the new tests fail. Should we include scipy in the test environment / requirements for Neo or is this introducing too strong dependencies? …
=> Add resample and decimate utility methods for Analog and IrregularlysampledSignals

neo/io/proxyobjects.py, neo/rawio/spike2rawio.py
RealWave channels were read as int32 instead of float32. 
Furthermore, logging wasn't imported in proxzobjects.py. This caused an error when the units were not recognized.
=> Fix reading RealWave Spike2 channels and channels with unrecognized quantities

doc/source/authors.rst, neo/core/analogsignal.py, neo/test/coretest/test_analogsignal.py
Dear all,
I have implemented an addtional function for the analogsignal class that should allow taking the absolute value of an analogsignal object without losing the annotations.
I have gone for a PR directly because I am indeed using this function already, it is working as expected. I thought it would be useful to have it available as a method.
Let me know your thoughts on it, or if something needs to be corrected.
Best,
Aitor
=> Add function to take the absolute value of analogsignals

neo/io/basefromrawio.py
This fixes the issue of getting a TypeError when loading a file with a RawIO, and an (array_)annotation is named like a ChannelIndex keyword argument, e.g., 'channel_names'. 
See the related Issue #786
=> make ChannelIndex creation in RawIO more robust

neo/test/test_utils.py, neo/utils.py
in the tests of the utils module filtering events and epochs using labels or any other regular attributes is not covered. #659 broke filtering by labels, but this wasn't noticed of course since the tests are missing. 
I fixed filtering by labels and added tests for labels and regular attributes.
=> Reenable Filtering Events and Epochs by Labels

neo/io/proxyobjects.py
When loading a new set of Spike2 files (from 2018), the IO couldn't handle the units 'µV'.
The changes add a corresponding conversion, fix a wrong conversion and a missing import, which was discovered while fixing this bug.
=> add micro Volt conversion and import missing package

neo/core/epoch.py, neo/core/event.py, neo/core/spiketrain.py, neo/test/coretest/test_epoch.py, neo/test/coretest/test_event.py, neo/test/coretest/test_spiketrain.py
The dimensions of time arrays of Event, Epoch and Spiketrains are frequently assumed to be 1-dimensional, e.g. see #801, but this is never enforced.
This lead to inconsistent behaviour with the introduction of array_annotations, which are always matching the last dimension of a data object. In cases when one of the objects above was initialised with a 2-dimensional array containing data only along the first dimension, this leads to array_annotations always being forced to be of length 1 even though there is more than one sample contained.
This PR enforces the time arrays of Events, Epochs and Spiketrains to be 1-dimensional via reshaping and adds corresponding tests.
=> Enforce times of Events, Epochs, Spiketrains to be 1d

neo/io/neuralynxio.py, neo/rawio/neuralynxrawio.py, neo/test/iotest/test_neuralynxio.py
This PR fixes #814 by introducing a new keyword argument for the NeuralynxIO.
For tests to succeed first https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/16 needs to be merged.
=> Add 'keep_original_times' keyword for NeuralynxIO

neo/rawio/axographrawio.py, neo/test/iotest/test_axographio.py, neo/test/rawiotest/test_axographrawio.py
``AxographRawIO`` should now be able to recover from unexpected end-of-file errors and text decoding errors if they occur when parsing sections of the header containing non-essential metadata. Warnings are logged in these cases, but the process should not fatally stall.
Previously, support for some AxoGraph files written by the independent [axographio](https://pypi.org/project/axographio/) Python package was missing. This has now been added. Namely, files written in the latest format version with a time vector (rather than a ``t_start, sampling_period`` pair using ``axographio.linearsequence``; these were already supported) can now be read.
Additionally, the reader will now check that time vectors are uniformly sampled, rather than just assuming they are.
Tests were added for all new …
=> AxographRawIO: Handle recoverable errors, support files written by axographio package

neo/io/blackrockio_v4.py
The legacy version of the BlackRockIO generates ChannelIndex objects with invalid `index` attribute. This prevents neo structures being read by this IO to be saved. This PR fixes this issue by making sure the `index` attribute is set properly.
=> Improve ChannelIndex generation in legacy BlackRockIO

neo/rawio/axonrawio.py, neo/test/iotest/test_axonio.py, neo/test/rawiotest/test_axonrawio.py
Hello,
A while ago, we switch equipment and I started getting the following error while trying to read any new ABF files:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.7/site-packages/neo-0.8.0.dev0-py3.7.egg/neo/io/axonio.py", line 45, in __init__
BaseFromRaw.__init__(self, filename)
File "/usr/lib/python3.7/site-packages/neo-0.8.0.dev0-py3.7.egg/neo/io/basefromrawio.py", line 81, in __init__
self.parse_header()
File "/usr/lib/python3.7/site-packages/neo-0.8.0.dev0-py3.7.egg/neo/rawio/baserawio.py", line 151, in parse_header
self._parse_header()
File "/usr/lib/python3.7/site-packages/neo-0.8.0.dev0-py3.7.egg/neo/rawio/axonrawio.py", line 62, in _parse_header
info = self._axon_info = parse_axon_soup(self.filename)
File …
```
=> added EDR3 header

neo/core/channelindex.py, neo/rawio/spike2rawio.py, neo/test/iotest/test_spike2io.py, neo/test/rawiotest/test_spike2rawio.py
In the CED documentation for the SON library, it says:
> In version 9 and above files, if pos is of type TDOF, the disk offset is pos*DISKBLOCK. In version 8 and previous files, the disk offset is pos. 
this PR fixes the offsets for v9 files, and fixes #818
=> fix for v9 SON files

neo/rawio/neuralynxrawio.py
Hi guys, I noticed a small bug in how empty or header only files are handled in NeuralynxRawIO. While empty .ncs files are skipped entirely and empty .nse and .ntt files are mapped to empty Numpy arrays, the current code attempts to memmap empty .nev files, which results in an error since the memmap offset is larger than the file size.
In contrast to .nse and .ntt files (see discussion on #553 ), I'm not convinced that empty .nev files are interesting enough to convey to the user, so I chose to handle them like the .ncs files, i.e. ignore them.
=> Fixed handling of empty .nev files in NeuralynxRawIO

neo/test/test_utils.py, neo/utils.py
Now cut_block_by_epochs give a new block and don't do a inplace replacement of segments.
Similarly to cut_segment_by_epoch.
See #755 
@mdenker @JuliaSprenger : could you check this ?
I think you are originals authors no ?
=> cut_block_by_epochs give a new Block now.

doc/source/install.rst
I've tweaked the install instructions as they were giving me trouble breathing: ``sudo pip install`` makes me go
Some other changes include explaining how to install the IO module dependencies and in general updating to more modern and recommended practices when using pip.
closes #862, closes #861
=> Updated install instructions to modern best practices

doc/source/core.rst, neo/io/asciiimageio.py, neo/io/baseio.py, neo/io/blkio.py, neo/io/brainwaredamio.py, neo/io/brainwaref32io.py, neo/io/brainwaresrcio.py, neo/io/tiffio.py, neo/test/iotest/test_brainwaredamio.py, neo/test/iotest/test_brainwaref32io.py, neo/test/iotest/test_brainwaresrcio.py
- added docstring
- fixed incorrect example in docs
- fixed inconsistency in Brainware IOs - read() now returns a list of Blocks
Fixes #762
=> Changes related to the `IO.read()` method

neo/core/basesignal.py
Running the function `imgseq.duplicate_with_new_data(imgseq.as_array())` fails because the signal attribute 'image_data' is returned as None by the `_get_required_attributes` function. Because the signal attribute for ImageSequence objects is not called 'signal' as assumed by the function an extra if statement needs to be added to make it work properly.
=> Fixing `duplicate_with_new_data` function for ImageSequence objects

neo/core/segment.py, neo/test/coretest/test_segment.py
Currently segment `t_start` and `t_stop` evaluation of a Segment fails in case of EventProxy or EpochProxy objects being present as these don't provide `times` values. However, in contrast to Events or Epochs these objects come with `t_start` and `t_stop` attributes, that can be used instead for the time range calculation of the segment.
This PR extends the `t_start` and `t_stop` calculation of Segments to be compatible with EventProxy and EpochProxy objects.
=> Make segment time evaluation compatible with ProxyObjects

neo/core/analogsignal.py, neo/test/coretest/test_analogsignal.py
This change allows the `AnalogSignal.time_index()` method to accept arrays of times, not just a scalar. If a scalar time is provided, the method returns a scalar index as before; if an array of times is provided, the method now returns an array of indices.
This is particularly useful with SpikeTrains:
```python
import neo
import quantities as pq
sig = neo.AnalogSignal(range(10)*pq.V, sampling_rate=1*pq.Hz)
st = neo.SpikeTrain([2, 4, 9]*pq.s, t_stop=10*pq.s)
indices = sig.time_index(st)  # previously would have needed to use something like
amplitudes = sig.as_quantity()[indices]
```
=> Vectorize AnalogSignal.time_index()

.gitignore, neo/rawio/neuralynxrawio.py, neo/test/iotest/test_neuralynxio.py
This set of changes fixes a bug which prevented the Pegasus .Nev event only files from passing the test suite. 
It also allows filename extensions to be in any letter case. For the InputInverted header parameter to be missing, 
meaning not inverted. Checks for 8 hashes at the start of the header as a check on header contents. Allows
any whitespace between a header key and value. 
Internal changes are addition of a large number of explanatory comments and refactoring of the code to handle
the header into a separate class. Many of these in preparation for handling earlier versions of neuralynx file headers
and more flexible handling of segments withins .Ncs files.
=> Fixes to make tests pass with Pegasus event files only directory.

neo/io/blackrockio_v4.py, neo/io/neuralynxio_v1.py
As discussed in #850 the non-raw versions of the Blackrock and Neuralynx IO will be deprecated for neo version 0.9 and removed with version 0.10.
=> Deprecate old Blackrock and Neuralynx IOs

neo/io/hdf5io.py
The code to reproduce the bug:
```python
import neo
hdf5neo = neo.io.NeoHdf5IO("dataset-1.h5")
block = hdf5neo.read_block()
```
`dataset.value` threw a deprecation warning in h5py v2.x and became an error in v3.0.0. Now it works for both h5py v2 and v3.
Deprecation warning in v2.x:
```
.../site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: 
"dataset.value has been deprecated. Use dataset[()] instead. Use dataset[()] instead.", H5pyDeprecationWarning)
```
Fixed error in v3.0.0
```python
1 hdf5neo = neo.io.NeoHdf5IO("dataset-1.h5")
----> 2 block = hdf5neo.read_block()
~/anaconda3/envs/temp/lib/python3.6/site-packages/neo/io/hdf5io.py in read_block(self, lazy, **kargs)
87         """
88         assert not lazy, 'Do not support lazy'
---> 89         return …
```
=> fixed a bug in loading hd5py data

neo/io/hdf5io.py
Currently hdf5io unittests are broken due to an update in the h5py API.
This PR fixes the IO by extending the first fix implemented in #892
=> Adapt to API change of h5py version 3.0

neo/io/nixio.py, neo/test/iotest/test_nixio.py
Currently, the `property.definition` attribute is used to tag both empty annotations and array annotations. This breaks down in the case of empty array annotations. 
I moved the array annotation tag to `property.type` which appeared to be unused as well, and I added a test with an empty array annotation. 
@achilleas-k is using the `property.type` attribute feasible / does that cause any other issues down the line? It only seems to work with `nixio<=1.5.0b3`.
=> Support Empty Array Annotations in NixIO

neo/test/test_converter.py
Now the names and numbers of groups and units are tested bidirectionally
This fixes the test fragment removed in 1ad87a8 that is also listed in #899
=> Extend test for ChannelIndex to Group and View conversion

neo/rawio/spike2rawio.py
Due to the fact that the header data is read using numpy using numpys fixed size integer types, any computation on them without a cast results in computations on this fixed size types, which can result in over- or underflows.
This can cause a bug in the `get_sample_interval` function of `spike2rawio.py`, where multiple `int32` numbers are multiplied, which, if they are large enough, can result in an overflow.
This PR fixes this bug by casting the first operant to `int`, so the multiplication is performed on pythons arbitrary size integers.
As this function returns a float, another possible solution would be to cast this into a float type, or, as it is later multiplied by the float 10^-6, to move that division to the front of the equation, resulting the other multiplications to be executed …
=> [BUGFIX] Integer Overflow in `spike2rawio.py`

neo/core/analogsignal.py, neo/core/baseneo.py, neo/core/basesignal.py, neo/core/irregularlysampledsignal.py, neo/test/coretest/test_analogsignal.py, neo/test/coretest/test_base.py, neo/test/coretest/test_irregularysampledsignal.py
This PR adds patch methods for AnalogSignals and IrregularlySampledSignals. Patching allows to combine signals along the time axis, so potentially across different Segments. The behaviour for IrregularlySampledSignal and AnalogSignals differs slightly, as for AnalogSignals overlapping sampling points are not possible in contrast to IrregularlySampledSignals, where all samples can just be combined irrespective of temporal overlaps. For AnalogSignals, the prioritized sampled can be specified using the `overwrite` keyword.
This feature can be for AnalogSignals extended to also handle padding during patching, therefore providing a solution to #820.
=> Add concatenate functionality for signal objects

.circleci/config.yml, neo/test/rawiotest/tools.py
CircleCI sometimes times out because no output is received for a long time while downloading files.
Here we try two approaches:
- increase no_output_timeout in config.yml
- use --debug flag to print output every time a file is downloaded
=> Attempt to remedy CircleCI timeouts

doc/source/rawio.rst, neo/rawio/baserawio.py
This new branch has only the changes in documentation and comments addressing the need to have groups of channels with the same t_start and signal_length as well as the use of the method to obtain these. 
Replaces PR #915 to have a cleaner history.
=> Rev raw io docs

setup.py
This change is needed for `setup.py` to discover the `neo/rawio/neuralynxrawio` directory. Otherwise, it is excluded from non-development installs (`python setup.py install` and `pip install .`), wheels (`python setup.py bdist_wheel`), and source distributions (`python setup.py sdist`).
Note that this was not a problem for development-mode installations (`python setup.py develop` and `pip install -e .`) because when installing from the repo the NeuralynxRawIO directory is, of course, already there. It's only when the other methods are used that the directory fails to be copied to the correct final location (e.g., into `site-packages` or the source tarball).
The automated CircleCI and Travis CI tests use `pip install .`, so one would expect them to catch this problem. However, this slipped …
=> Include NeuralynxRawIO directory in non-develop installs, wheels, and source distributions

doc/source/grouping.rst
Brackets are needed around `spiketrain` in `Group(spiketrain, ...)` to prevent this:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-d6cd90dbfc95> in <module>
22 units = []
23 for i, spiketrain in enumerate(spiketrains):
---> 24     unit = Group(spiketrain, name=f"Neuron #{i + 1}")
25     units.append(unit)
26
c:\users\jeffrey\documents\python-dev\neo\git-repo\python-neo\neo\core\group.py in __init__(self, objects, name, description, file_origin, allowed_types, **annotations)
53         else:
54             self.allowed_types = tuple(allowed_types)
---> 55         if objects:
56             self.add(*objects)
57
ValueError: The truth value of an array with …
```
=> Fix broken example in Group docs

neo/io/elanio.py, neo/rawio/elanrawio.py
Hi,
I'm using Neo for reading Elan files (.eeg, .ent, .pos). However, by default the class only support the same base name for all three  files. In my case, they have different names and unfortunately I'm not allowed to change it.
In addition to that, maybe the default event encoding changed, but the events are not correctly detected.
=> Allow passing full path to ENT and POS files to ElanIO + fix event detection

neo/rawio/openephysrawio.py, neo/test/rawiotest/test_openephysrawio.py
In old implementation channel order was not the natural one.
"CH" channels where put after the "ADC" channels. This was the total inverse of the sofwtare.
This put the good order.
=> Good channel order for old openephys format.

neo/io/igorproio.py
Add support for IgorIO.read(), read_block(), read_segment() for .pxp files (currently only read_analogsignal() works for such files)
Unfortunately, the only test file I have to hand is 480 MB, which I think is too big to add to the test file repository. Does anyone have any smaller .pxp files we could use for automated testing?
=> Improvements to support for .pxp files by IgorIO

neo/rawio/axonarawio.py
The goal was to match indexing schemes of channels and tetrodes to that used in the .set file (for an example see [here](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/axona/axona_raw.set)).
Within `raw_annotations['blocks'][0]['segments'][0]['signals'][0]['__array_annotations__']`:
`channel_names` were 0-indexed (0a, 0b, 0c, 0d, 1a, 1b, ...), and are now 1-indexed, because the numbers reflect tetrodes, which are 1-indexed in the .set file. 
`channel_ids` were 1-indexed (1,2,3, ...), and are now 0-indexed (0,1,2, ...), because channels are 0-indexed in the .set file. 
Note that in spikeextractors we will use 0-indexing for both channels and tetrodes to keep the convention consistent within spikeextractors between different file formats: …
=> made channel_names annotation 1 indexed in line with axona file format

.github/workflows/full-test.yml, README.rst
This PR updates the badges as they are included in the readme.rst.
It removes the broken requirements badge and replaces the CI badge with a new badge generated upon any merge into the master branch.
As the new CI configuration is not run yet in this PR, the new badge is not yet created, but will (hopefully) once merged.
@samuelgarcia What do you think?
=> Update CI badge

neo/rawio/spikeglxrawio.py
This PR fixes .meta line parsing using the solution from the [Probe Interface project](
https://github.com/SpikeInterface/probeinterface/blob/19d6518fbc67daca71aba5e99d8aa0d445b75eb7/probeinterface/io.py#L649-L662). I also make parsing of .meta conditional, since it should only be done when .bin with a matching name is present.
=> [spikeglxrawio] .meta file parsing fix

neo/io/baseio.py, neo/io/igorproio.py, neo/io/nixio.py, neo/rawio/axonarawio.py, neo/rawio/blackrockrawio.py, neo/rawio/elanrawio.py, neo/rawio/nixrawio.py, neo/rawio/tdtrawio.py, neo/test/iotest/common_io_test.py, neo/test/iotest/tools.py
All IOs implicitly assume that the file and directory names provided are strings. Therefore many IOs fail, when a path specified as a [pathlib](https://docs.python.org/3/library/pathlib.html) object is provided instead. This PR introduces the automatic conversion of filenames and directory names, for all IOs and adds a common IO test.
=> Accept file and path names to be pathlib objects

neo/rawio/neuralynxrawio/ncssections.py
Factored out the temporary variables of CscRecordHeader used in Ncs record scanning. Algorithm now reads directly from the memmap which is passed around. No allocation of an object within the loop. Hopefully this will eliminate the curious memory leak noted in issue #971.
=> Eliminate CscRecordHeader

neo/rawio/axonarawio.py, neo/test/iotest/test_axonaio.py, neo/test/rawiotest/test_axonarawio.py
This PR implements the required rawio methods for reading spiketimes and waveforms. It also restructures the IO to be able to support multi-file datasets (.bin & unit files).
This PR depends on the Axona unit test data that will be added to the ephy_testing_data: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/49/files
=> Enable AxonaIO to read spiketimes and waveforms

neo/rawio/phyrawio.py, neo/test/rawiotest/test_phyrawio.py
This PR fixes some issues with PhyIO. 
Changes:
* Numeric spiketrain annotations are int or float (used to be str)
* Added `cluster_id` annotation (corresponds to id annotation, but is int, not str)
* PEP 8 fixes
=> [phyio] Fixed spiketrain annotations

neo/rawio/cedrawio.py
@eduardacenteno : could you test this on your data ?
=> Add read spike times in CedIO

neo/rawio/maxwellrawio.py
In some older files, the `lsb` field might not be present in settings. In that case, the `gain_uV` can be computed as:
`gain_uV = 3.3 / (1024 * gain) * 1e6`
where `gain` is the amplifier gain, 3.3 is the ADC voltage range, and 1024 (10^10), is the number of bits of the ADC.
=> Fix Maxwell gain when 'lsb' is not in settings

neo/test/utils/test_misc.py, neo/utils/misc.py
=> [utils] do not copy nix_name annotation to different object types

neo/rawio/blackrockrawio.py
=> fixing small list comprehension error

neo/rawio/winwcprawio.py
Small fix for winwcp files.
The sampling rate can be slightly over segment due to float precision.
The previous implementation  raise error for some random files.
=> Small fix for winwcp files.

neo/test/iotest/test_nixio_fr.py
With nixio version 1.5.1 labels can only be string and not binary any more, as should now also be the case when loading data with a neo.io.
=> fix tests with latest nixio release

requirements_testing.txt
Datalad version 0.15.0 and later requires a git-annex version that is not in the ubuntu default packages yet.
See also https://github.com/datalad/datalad/commit/315911ca76687ef0b8a529f0dfa99bf25fe040ba
=> [CI] pin datalad version

doc/source/developers_guide.rst, doc/source/governance.rst
The purpose of this document is to formalise how decisions are taken in the project, so that people who may wish to contribute to the project have clear expectations.
=> Add a document describing project governance

requirements_testing.txt
The latest nixio version (1.5.2) raises an error when rewriting string annotations.
This should be resolved on the nixio level.
=> [nix] pin nixio to avoid buggy 1.5.2 version

neo/io/spikeglxio.py, neo/rawio/spikeglxrawio.py, neo/test/iotest/test_spikeglxio.py, neo/test/rawiotest/test_spikeglxrawio.py, requirements_testing.txt
* Support for neuropixel 2.0
* clean
* remove location (because wring in neo) use prointerface for correct channel location
* add `load_sync_channel` option to not load the last channel
See #1028
=> Spikeglx np2

neo/rawio/spikeglxrawio.py
In the SpikeGLX parser, gains are wrongly set.
In the SpikeGLX documentation (https://github.com/billkarsh/SpikeGLX/blob/gh-pages/Support/Metadata_20.md#channel-entries-by-type):
`g = Vmax / Imax / gain`
but in the code it was set as (https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/spikeglxrawio.py#L287):
`g = gain * Vmax / Imax` 
where `Vmax / Imax` is `gain_factor `. Instead, it should be:
`g = Vmax / Imax / gain`
This is tested on a NP2 file, where the computed gainwas over 4000! With the corrected gain, it is now ~0.7, which gives more reasonable uV values.
=> Fix gains for SpikeGLX

neo/io/stimfitio.py, neo/test/iotest/test_stimfitio.py
This PR fixes a particularly elusive bug observed when a MNE-Python example that uses `neo` was being built by sphinx-gallery but its namespace variables were not able to be cleared by calling `gc.collect()` after example execution completed. The root cause turned out to be that the `import neo` in the example led to an import of `neo.io.stimfitio` (okay by itself), which in turn tried to import `stfio` which failed (okay by itself), which in turn kept the variables in memory in the traceback frame of the exception so that they could not be garbage collected (bad!). Or, in simplified-example form, this was problematic:
```
>>> import numpy as np
>>> x = np.ones(123456789)
>>> import neo
>>> print(neo.io.stimfitio.STFIO_ERR.__traceback__.tb_frame.f_back.f_back …
```
=> BUG: Dont hold the exception

neo/rawio/neuroscoperawio.py
This should fix #1077 
As described, the loop in the diff assigns groups to channels assuming that everyone channel as a group name. As described in #1077 this is not the case. The code provides a simple default for those cases.
=> Assign a default value to group-less channels in NeuroScopeRawIO 

neo/rawio/tdtrawio.py
Currently if a the last data block of a chunk is loaded and all of it's samples are valid (need to be included), then None is included, due to wrong indexing (`data[:-length]` instead of `data[:]`)
=> [tdt] fix border id handling for chunk loading

neo/rawio/axonarawio.py, neo/rawio/biocamrawio.py
A couple of small fixes that came up when addin tests in SI:
- BiocamRawIO: remove squeeze when returning traces
- AxonaRawIO: construct list of channels also when `channel_indexes` is a `slice`
=> Fixes from SpikeInterface CI

.readthedocs.yaml, LICENSE.txt, README.rst, doc/source/conf.py, doc/source/releases/0.10.1.rst, doc/source/whatisnew.rst, neo/version.py
Currently the documentation is not building due to the documentation requirements being unaccessible. For me it seems the file is there (https://readthedocs.org/projects/neo/builds/16245520/). @samuelgarcia Any idea?
=> 0.10.1 release updates

requirements_testing.txt
See original pinning, see #1063
Closes #1085
=> unpin nixio version as fix was released in version 1.5.3

neo/rawio/tdtrawio.py, neo/test/iotest/test_tdtio.py, neo/test/rawiotest/test_tdtrawio.py
This PR includes the recently added TDT testdatasets into the neo tests. (https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/73 and https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/74)
To parse these new files correctly also the header parsing regex needed to be restricted to not accept non-ascii characters in name or type strings.
This PR is building on top of #1070.
=> [tdt] Add new entities to tdt tests and fix file header parsing

neo/rawio/spikeglxrawio.py
Refactor a bit function for exploring meta data.
This is needed (quite urgently) for spikeinterface internal mainly.
@JuliaSprenger @alejoe91
=> [spikeglx] Refactor function for exploring meta data.

neo/io/__init__.py, neo/io/edfio.py, neo/rawio/__init__.py, neo/rawio/edfrawio.py, neo/test/iotest/test_edfio.py, neo/test/rawiotest/test_edfrawio.py, requirements_testing.txt, setup.py
This IO supports reading files in the European Data Format (EDF, https://www.edfplus.info/). For now only original EDF files and EDF+ files with continuous data (EDF+C) are accepted. The IO is based on the pyedflib package.
=> Add EDF IO

neo/core/analogsignal.py, neo/test/coretest/test_analogsignal.py
The traceback was:
```
File "/Users/andrew/dev/simulation/PyNN/pyNN/utility/plotting.py", line 89, in plot_signals
ax.plot(signal.times.rescale(ms), signal, label=label, **options)
File "/Users/andrew/.conda/envs/simulation/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
lines = [*self._get_lines(*args, data=data, **kwargs)]
File "/Users/andrew/.conda/envs/simulation/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 273, in __call__
yield from self._plot_args(this, kwargs)
File "/Users/andrew/.conda/envs/simulation/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 389, in _plot_args
y = _check_1d(tup[-1])
File "/Users/andrew/.conda/envs/simulation/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1318, in _check_1d
ndim = x[:, …
```
=> Fix exception raised when calling pyplot.plot(sig.times, sig) if the signal has array annotations

.github/workflows/io-test.yml, environment_testing.yml, neo/test/iotest/test_edfio.py, requirements_testing.txt
This should fix #1115, by installing more recent versions of datalad and git-annex.
Analogous to the current version, the conda environment is cached and only rebuild when one of the requirement files changes or a new month started. The execution time of the tests when everything is already cached is the same as before (~12 minutes).
=> [CI] use conda environment for IO tests

neo/io/neurosharectypesio.py, neo/test/iotest/test_neuroshareio.py
The tests were only run on windows and did not use the test file available. To make the tests pass with the current neo and python version I also had to add some small fixes in the neurosharectypesio.
=> [neuroshare] extend tests also to linux and IO fixes

neo/io/neomatlabio.py, neo/test/iotest/test_neomatlabio.py
=> Add support for IrregularlySampledSignal in NeoMatlabIO

neo/io/nwbio.py, neo/test/iotest/test_nwbio.py
@legouee @apdavison What do you think of these changes?
=> Enable NWBIO to write lazy data objects

neo/rawio/spikeglxrawio.py
I came across some pair of spikeglx imec output files that have different value of filesize (of the `.bin`) file than that retrieved from the `.meta` file.
While this may be a faulty .meta file, but I think an exception should be thrown while parsing such a file.
=> Spikeglx filesize check

.github/workflows/core-test.yml, doc/source/install.rst, neo/test/tools.py, setup.py
following the [NEP](https://numpy.org/neps/nep-0029-deprecation_policy.html)+1 policy (upcoming July 26th change)
=> Update CI matrix for core tests

doc/source/conf.py, neo/io/neomatlabio.py, neo/io/nixio.py, neo/rawio/intanrawio.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/iotest/test_blackrockio.py, requirements.txt, setup.py
=> Replace distutils.version with packaging.version

README.rst, neo/rawio/tdtrawio.py
This change should reduce the warning output of our current testsuite drastically.
=> clean up tdt warnings and badge cleanup

doc/source/core.rst, doc/source/developers_guide.rst, doc/source/grouping.rst, doc/source/index.rst, doc/source/io.rst, doc/source/io_developers_guide.rst, doc/source/rawio.rst, doc/source/usecases.rst, doc/source/whatisnew.rst
This is a quick sweep of the documentation for some quick fixes:
- fixes some examples that showed python2 style print
- update the minimum python version listed in the developers guide that lagged behind current requirement
- fix typos in the doc pages
=> [DOC] - Small fixes to documentation

neo/rawio/openephysbinaryrawio.py
This patches improves the parsin of multi-experiment Open Ephys binary folders. 
The previous implementation had two major problems:
1. the `explore_folder` assumed that experiments and recordings were looped through in a sorted order, but this is not the case. With this patch, the `nb_segment_per_block` is a dictionary instead of a list and it is associated to each block_index by key.
2. Streams can change in two or more experiments. The previous implementation assumed that the streams from the first block were the same of other blocks, but again this is incorrect. With this patch, streams from different blocks are treated separately and assigned a different `stream_index`.
=> Fix Open Ephys block parsing

neo/io/igorproio.py, neo/io/klustakwikio.py, neo/io/kwikio.py, neo/io/neomatlabio.py, neo/io/nixio.py, neo/io/nwbio.py, neo/io/tiffio.py, neo/rawio/baserawio.py, neo/rawio/biocamrawio.py, neo/rawio/cedrawio.py, neo/rawio/maxwellrawio.py, neo/rawio/mearecrawio.py, neo/rawio/nixrawio.py, neo/test/iotest/test_klustakwikio.py, neo/test/iotest/test_kwikio.py, neo/test/iotest/test_neomatlabio.py, setup.py
This PR remove unnecessary import at module level and import extra dependency only when they are needed when instanciating an IO class.
See #1160
This should:
* help in complicated environement (by not importing everything)
* decrease import duration
The drawback:
* it raise error only when instanciate (run time) and not at load time.
=> Local import and remove HAVE_PACKAGE logic

neo/rawio/spikeglxrawio.py
@JuliaSprenger : I spent 3 days working on truncated dataset of spikeglx (they record overnight and select only some periods)
I can tell that that the warning is really annoying and useless!!
So I remove it
:)
=> remove fileSizeBytes warning

neo/rawio/openephysbinaryrawio.py, neo/test/rawiotest/test_openephysbinaryrawio.py
This PR improves the checks the `OpenEphysBinaryRawIO` by:
1. pre-mapping folder structure in terms of recording nodes, experiments, and recordings
2. assigning `block_index` and `seg_index` after pre-mappping (it is possible that some experiments/recordings are deleted by the user because of errors etc.)
3. adds checks to ensure that:
- experiments (blocks) are consistent acrosse multiple nodes (if present)
- streams are consistent across recordings (segments)
- the same streams are present in all experiments (blocks)
In case the latter check fails, there is a new option to use the argument `experiment_names` to select a subset of experiments with consistent streams to be loaded.
=> Openephys check consistency experiments

neo/rawio/openephysbinaryrawio.py, neo/test/rawiotest/test_openephysbinaryrawio.py
This PR adds the `load_sync_channel` (True by default) to avoit loading the SYNC channel in Open Ephys Neuropixels recordings (similar logic to SpikeGLX).
Based on: https://github.com/NeuralEnsemble/python-neo/pull/1159
=> Add `load_sync_channel` logic to OpenEphysBinaryRawIO

neo/rawio/neuralynxrawio/neuralynxrawio.py
This permits extracting file metadata as io attributes. External tools don't need to parse file headers to retrieve additional, non-annotated metadata.
=> [neuralynx] expose parsed version of file headers

setup.py
to install all optional requirements (helpful for setting up development environments)
=> Add a "pip install neo[all]" option

neo/core/epoch.py
in which case the duration units will be taken from the `units` argument or from the units of the `times` argument.
=> Allow epoch duration to be a float

neo/rawio/phyrawio.py, neo/test/rawiotest/test_phyrawio.py
PhyIO automatically loads csv files in the data folder, but assumes that they only have two columns. This causes an error e.g. when loading a SpikeInterface folder with quality metrics which are saved in a single multi-column 'metrics.csv' file.
I extended the csv loading routine to allow for multiple columns, and while doing that I noticed that negative floats currently cause an error since they are not covered by the regular expression that is being used to detect floats, so I fixed that, too. 
Additionally, I added tests covering the multi-column and negative float cases.
=> Read multi-column csvs in PhyIO

neo/rawio/openephysbinaryrawio.py
The Open Ephys event channel ids were set to the `stream_index`, which made it not very informative.
This PR sets the event `id` to be the same as the event `name`: e.g. `Message Center`, `PXIe`, `RhythmFPGA`, etc.
=> Better `id` for Open Ephys Events

neo/rawio/blackrockrawio.py, neo/test/iotest/test_blackrockio.py, neo/test/rawiotest/test_blackrockrawio.py
Closes #795 
[Blackrock_FileSpec_3_0.zip](https://github.com/NeuralEnsemble/python-neo/files/9689684/Blackrock_FileSpec_3_0.zip)
=> BlackrockRawIO FileSpec 3.0

doc/source/releases/0.11.1.rst, doc/source/whatisnew.rst, neo/version.py
This PR updates the release notes and version number for 0.11.1
Anticipated release date is the 21st October.
@samuelgarcia @apdavison Do you have something to add? It would be ideal if we could find a solution for #1184  before the release.
=> Preparing release of version 0.11.1

.github/workflows/core-test.yml, doc/source/developers_guide.rst, doc/source/install.rst, neo/test/coretest/test_base.py, requirements.txt, setup.py
- drop support for Python 3.7
- drop support for numpy 1.18
=> update test matrix following NEP29 + 1 year

neo/io/nwbio.py
Hi @legouee!
I had discovered that you are closing all io instances except for one in the NWBIO and that you have an instance variable `_nwb_io` that looks like it's intended for referencing the opened io. Here I added the functionality to close the io that has been used for reading. Can you have a look and see if this is what you intended originally?
=> [NWB] enable closing of dangling file io

neo/rawio/intanrawio.py
This is my first stab at incorporating a flag so that users can see whether or not their data has already had a notch filter applied. I couldn't think of a way to get it incorporated during the flow of the rest of the script, so I added the check right before the return to generate the flag.
@samuelgarcia
=> Add a flag for intanrawio indicating whether intan hardware has already applied a notch filter to raw data

.github/workflows/io-test.yml
Currently the cached ephys data do not contain the latest hash in the caching key as the hash is not correctly forwarded to the github output variable.
=> Fix caching of testing data in CI

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/nlxheader.py
Neo didn't recognize the "RawDataFile" acquisition type in the header string. This is set when ".ncs" files are created by an offline replay of Neuralynx raw data (".nrd") files. 
I also commented on the bug in issue#1202
=> added RAWDATAFILE to neuralynx type_of_recording

.github/workflows/caches_cron_job.yml, .github/workflows/core-test.yml, .github/workflows/io-test.yml
This PR introduces a dedicated cron job for cache creation to be used in IO tests, based on the CI tests in [spikeinterface](https://github.com/SpikeInterface/spikeinterface/blob/master/.github/workflows/caches_cron_job.yml).
It also reduces the number of tests run by executing Neo core tests only if core files or dependencies changed.
@samuelgarcia @h-mayorquin What do you think of this setup?
=> Improve CI speed

neo/io/nixio.py
The datetime formatter `%s` is not available on Windows systems, `int(datetime.timestamp())` yields the same information OS independently.
=> [NixIO] use OS independent datetime formatting

neo/rawio/spikeglxrawio.py
Added support for SpikeGLX recordings using [1.0-NHP Neuropixels probes](https://www.neuropixels.org/_files/ugd/328966_97dfdcf9421a41ae9c57c9047928834c.pdf) as per this issue in spikeinterface/spikeinterface#1431 and [SpikeGLX source](SpikeGLX/Src-imro/IMROTbl.cpp)
Tested on a recording acquired with default settings using SpikeGLX release v20230120-phase30 and  45mm (long) 1.0-NHP Neuropixels probes with imDatPrb_type=1030
=> spikeglxrawio.py updated to support 1.0-NHP probes

neo/rawio/openephysbinaryrawio.py
=> Check 'states' length before inferring event durations

doc/source/core.rst, doc/source/developers_guide.rst, doc/source/io.rst, doc/source/io_developers_guide.rst, doc/source/rawio.rst
I just noticed a few typos on the documentation so just made  a few corrections.
=> Fixed Documentation Typos

doc/source/developers_guide.rst, pyproject.toml
joblib is used in `BaseRawIO.__init__` and is a hard dependency if caching is used (#1224). I therefore added it to the project's dependencies.
=> Add joblib dependency

neo/rawio/spikeglxrawio.py
=> spikeglx naming debug #1240

neo/rawio/baserawio.py, pyproject.toml
Since we only use a single feature of joblib, and in only one place, where it is optional, I thought it would be better not to install it by default.
=> Make joblib an optional dependency

neo/rawio/spikeglxrawio.py
#1246 have broken spikeinterface and neuroconv tests.
Here a fix that should be OK.
=> Fix for spikeglx to repair #1246

neo/io/mearecio.py, neo/rawio/baserawio.py, neo/rawio/mearecrawio.py, neo/test/rawiotest/test_mearecrawio.py
Right now `MEArecRawIO` loads all the data (recording and sorting) by default. This PR leaves that default as it is but also adds the option of only loading recording or sorting data with a boolean value at `__init__`. 
With this, the intialization of the object -specially the recoder- should be lighter as it does not need to go through the spiking data in mearec.
I added tests for both of these modes.
=> Add option to `MEArecRawIO` for loading only recordings or only sorting data

neo/core/segment.py
This PR removes the reference to the `all_data` property in the docstring of the neo.core.Segment class. 
https://github.com/NeuralEnsemble/python-neo/blob/ac0d9e6fab1094226610603099b635a7bf53d230/neo/core/segment.py#L65
In pull request #143, the `all_data` property was removed from the class, but the description of the property remained in the docstring. This could be confusing for users who come across the docstring and try to use the all_data property, which is no longer available.
This change does not affect the functionality of the code, but it will improve the clarity and accuracy of the documentation, which is why I considered to add this here.
Feel free to close this PR any time, this is just meant to inform you about this finding. :slightly_smiling_face:
=> Remove reference to all_data property in docstring of class Segment

doc/source/install.rst, neo/io/igorproio.py, neo/test/iotest/test_igorio.py, pyproject.toml
Because the latter is no longer maintained, and produces errors with recent versions of NumPy
=> Use igor2 in place of igor

neo/io/pickleio.py
I encountered this today while debuggin some issue.
Python 2 is long gone:
https://devguide.python.org/versions/
=> Remove pickle python 2 library

neo/rawio/alphaomegarawio.py
When running pytest I keep getting this:
``` python
\neo\rawio\alphaomegarawio.py:1: DeprecationWarning: invalid escape sequence \*
```
So this is a pull request just to fix the docstring. It is the only DeprecationWarning I'm getting currently so should be an easy fix.
=> Fix DeprecationWarning during Testing due to invalid escape character

neo/rawio/examplerawio.py
Was checking out the new documentation--theme looks great by the way and saw a few typos.  This just fixes those.
=> Fixed a few typos in ExampleRawIO

neo/test/iotest/test_nixio.py
The float comparison seems to fail only on GH actions. This solves #1277.
@samuelgarcia Can you have a look and merge this together with #1274 to not have failing CI tests in master any more?
=> [NixIO] Relax criteria for float comparison

neo/io/asciisignalio.py, neo/test/iotest/test_asciisignalio.py
This PR clarifies the relation between `timecolumn` and `usecol` and covers the case in which `timecolumn` is included in `usecol`. In this case the time column channel index does not require to be annotated. This leads to incorrect dimensions of the array annotations in the current master branch.
=> [AsciiIO] Fix handling of handle channel index array annotations

neo/rawio/neuroscoperawio.py
I am working on using this reader for a conversion and I found the logic for deciding how to load the binary file and the xml file quite confusing. To improve this I have done two things:
1) Add a descrition of the path resolution logic in the docstring.
2) Refactor the path resolution logic (without changing) to make it more readable.
Also, I don't know why but the filename was equal to an empty string by default. I don't know if anyone use this default but that would have resulted in an error on the previous implementation. Is this something that is intentional for reasons of the non-raw-io part of neo?
=> Improve neuroscope documentation and refactor path resolution

neo/core/dataobject.py, neo/test/coretest/test_dataobject.py
Currently annotations do accept values of type `tuple`, but array annotations don't. This PR adds tuples to the accepted type of data for the creation of array annotations.
=> Accept array_annotation values of tuple type

neo/io/__init__.py, neo/test/iotest/test_get_io.py
Fixes #1287 
Rather than check if the file exists it now just checks that a suffix is provided. If a suffix is provided whether the file already exists or is a future file it returns the potential ios that would support that file format. The rest of the logic for checking for potential ios remains the same.
=> update get_io to return ios for files that do not exist yet

neo/io/proxyobjects.py, neo/test/iotest/test_proxyobjects.py
In #1017 there is a discrepancy between 
`lazy=True` vs `lazy=False` because one uses `AnalogSignal` and one uses `AnalogSignalProxy`. This is likely due to the fact that `AnalogSignalProxy` is missing an `np.ceil` when calculating the `i_stop` which is included when calculating `i_start`. `AnalogSignal` accomplishes this with `np.rint` which when including the `astype(int64)` does the same as `int(np.ceil())`
https://github.com/NeuralEnsemble/python-neo/blob/53b202b2a6ae306392063d1dd2438323b4815de3/neo/io/proxyobjects.py#L191-L204
Let me know if you want a test added for this.
=> ensure analog signal proxy and analog signal behave the same for time slices 

.github/workflows/io-test.yml, .github/workflows/io-test_dispatch.yml, .github/workflows/io-test_trigger.yml
This PR adds the option to manually trigger the IO test suite and select the operation system to run the test on.
The automatic triggering of the IO tests always uses 'ubuntu-latest' as operating system. In the manual trigger it is possible to specify also `macos-latest` and `windows-latest` as operation systems.
Most likely the test suite won't pass for the other operation systems with the current test setup, but this will need a 2nd PR for debugging.
=> add workflow dispatch to manually trigger io tests on non-ubuntu os

neo/test/iotest/test_proxyobjects.py
I forgot that we should add this test with pull request #1298. This adds a test where we give a t_start that needs to be rounded down
=> Add round down test to analogsignal proxy

doc/source/authors.rst, neo/core/container.py, neo/core/group.py, neo/test/coretest/test_block.py, neo/test/coretest/test_group.py, neo/test/coretest/test_segment.py
e.g.
```python
In [1]: from neo import Block, Segment
In [2]: segment = Segment()
In [3]: segment.add(Block())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 segment.add(Block())
File ~/dev/neo/neo/core/container.py:355, in Container.add(self, *objects)
353     container.append(obj)
354 else:
--> 355     raise TypeError(
356         f"Cannot add object of type {obj.__class__.__name__} "
357         f"to a {self.__class__.__name__}, can only add objects of the "
358         f"following types: {self._child_objects}"
359     )
TypeError: Cannot add object of type Block to a Segment, can only add objects of the following types: ('AnalogSignal', 'Epoch', 'Event', …
```
=> Check the types of objects added to a container with the new `add()` method

neo/rawio/maxwellrawio.py
Fix for issue [https://github.com/SpikeInterface/spikeinterface/issues/1691](url) that shuffled channels when selecting and concatenating channels from MaxWell recordings with different mappings.
=> Fixed bug in maxwellrawio.py that shuffled channels 

neo/rawio/openephysbinaryrawio.py
Fix #1199
- Allow loading of OE bunary fodlers without events or consinuous streams
- More informative error message if `structure.oebin` files are not found ("not a valid Open Ephys binary folder")
=> Allow folders without events/continuous streams to be loaded

neo/test/rawiotest/test_get_rawio.py
After working on #1297 and @JuliaSprenger adding tests I thought it would be nice to mirror the same type of tests for the `get_rawio_class`. The two tests I've added are:
1) First test is for a supported file format which should return a reader
2) The second is for a non-supported file format which should return None
One question I wanted to bring up is that currently `neo.io` has a function `get_io` whereas `neo.rawio` instead has a `get_rawio_class` instead. It might be more parsimonious to change to `get_rawio` instead, but rather than just make that change I wanted to ask for opinions first. Happy to add here or raise an issue if that is preferred.
=> Add test for get_rawio_class

neo/rawio/blackrockrawio.py, neo/rawio/spikegadgetsrawio.py, neo/utils/misc.py
Quoting @zm711 in spikeinterface:
> Just wanted to put this on everyone's radar. Not sure when this will be a hard error. I assume in a few versions (similar to the np.bool/np.float which deprecated in 1.20 and hard errored in 1.24)
> https://numpy.org/devdocs/release/2.0.0-notes.html
This PR takes care of this:
=> `np.in1d` to `np.isin` as the former will be deprecated 

neo/rawio/__init__.py, neo/test/rawiotest/test_get_rawio.py
As discussed in #1317 and in #1322. 
This just harmonizes the `get_io` and `get_rawio` functions while adding an alias to protect previous users.
=> Change `get_rawio_class` to `get_rawio`

neo/io/klustakwikio.py
Hi!
I was working with some older KlustaKwik datasets and was wondering why NEO wasn't loading them. Turned out the culprit was an overly strict regular expression that was only matching single words.
This patch fixes that, so filenames like "ec013.395.clu.1" are considered valid too.
Thanks for considering!
Matthias
=> klustakwikio: Adjust regular expression to catch more filenames

.github/workflows/io-test.yml
Fixes some failing tests from Maxwell due to the non-existence of the default HDF5_PLUGIN_PATH folder
=> Set HDF5_PLUGIN_PATH to a folder existing on GH CI

neo/rawio/axonrawio.py
Found by @ctigaret, but then the PR was closed. So either that one can be merged if reopened or this one could be merged to fix the typo in the rawio.
#1325
=> Fix `format` typo in axonrawio assert statement

neo/rawio/biocamrawio.py, neo/test/iotest/test_biocamio.py, neo/test/rawiotest/test_biocamrawio.py
=> Add support for Biocam brw v4.x files, closes #1324

neo/core/analogsignal.py, neo/core/baseneo.py, neo/core/basesignal.py, neo/core/container.py, neo/core/dataobject.py, neo/core/epoch.py, neo/core/event.py, neo/core/group.py, neo/core/imagesequence.py, neo/core/irregularlysampledsignal.py, neo/core/spiketrain.py, neo/core/spiketrainlist.py, neo/io/basefromrawio.py, neo/rawio/baserawio.py
I switched a lot of the `.format` and some of the `%` to f-strings. Neo is 3.8 + right now and f-strings were introduced in 3.6.  They are faster (~ 1.5-2x compared to format) and at least to some, myself included, more readable. 
I didn't touch any of the ios/rawios in this PR.
Take a read and let me know what you think.
=> Switch Neo specific Code to F strings

neo/rawio/plexon2rawio/plexon2rawio.py
Currently plexon download is fixed to use the 32 bits architecture. This means that plexon is not working if the windows machine is 64 bits. This PR fixes this by adding code that checks the architecture and selects the appropriate file to download based on that query.
There is a warning that I think should be removed in the code. Let me know what you think.
[EDIT] it seems that wine on linux uses the 32 bit architecture (I wonder why?) so I added code that restricts the 64 dll only for windows which does make sense anyway.
=> Download correct ddl for 64 system on windows with Plexon

neo/rawio/blackrockrawio.py
This is just a minor deprecation fix PR that I saw while running the test suite.
=> Switch `np.math.ceil` to `math.ceil` as the former is deprecated as of NumPy 1.25

neo/core/group.py, neo/test/coretest/test_group.py
as proposed in #1026, which this PR partially replaces
=> do not allow Groups to contain Segments

neo/rawio/biocamrawio.py
Just realized that through the talks around #1326 and #1348, this (very) small fix got lost.
I've never personally encountered a BrainWave recording with inverted signal, but it might be the case for older files.
=> Fix signal inversion in BioCAM IO

.github/workflows/publish-to-pypi-test.yml, .github/workflows/publish-to-pypi.yml
As discussed, this PR adds two actions for releasing NEO:
1. `Release to Test PyPI`: this action is run at every tag and it:
- checks that `neo.__version__` corresponds to the `tag`
- uploads to Test PyPI (added an environment secret `TEST_PYPI_API_TOKEN`) 
2. `Release to real PyPI`: this action needs to be triggered manually (after the test pypi action succeeded), to upload to PyPI
@apdavison can you add me as maintainer of the `neo` package on Test PyPI?
=> Add workflow actions for automated release to PyPI

neo/rawio/plexon2rawio/plexon2rawio.py
Fixes #1371.
As explained in the issue the structures are indexed different so we need to +1 to correctly index. Add comment to explain this with links.
=> Plexon2: Fix conversion between C++ tm structure and python datetime

neo/rawio/openephysbinaryrawio.py
This PR makes the OpenEphysBinaryRawIO reading of events compatible  with the format used before v0.6 of the Open Ephys GUI
=> Open ephys RawIO back compatibility for events

neo/core/baseneo.py, neo/io/baseio.py, neo/rawio/baserawio.py, neo/rawio/examplerawio.py
Replaces #1229 because that now has merge conflicts.
I know this has been discussed #1123. Sam is against, others are typically for. This is just a draft to think about (& correct or reject), but I think adding type hints to some places exposed to the user would be beneficial. By putting the hints into the base it propagates to all ios to minimize other typing needing to be added, although developers can override the typing in their specific io.
I know that neo has complicated inputs, but I think type hints work best to give a suggested appropriate input (And as a nod to Sam I didn't add type hints for the returns yet).
=> Add Typing to `baseio`, `baserawio`, and `exampleio`

neo/core/baseneo.py, neo/core/block.py, neo/core/group.py, neo/core/imagesequence.py, neo/core/regionofinterest.py, neo/test/coretest/test_group.py, neo/test/coretest/test_imagesequence.py, neo/test/coretest/test_regionofinterest.py
i.e. the ROI
- contains a reference to the underlying data object
- is not stored in a Block directly
- can be stored in a Group
- can have annotations
This partially replaces #1026
=> make the handling of RegionOfInterest subclasses consistent with ChannelView

.github/workflows/publish-to-pypi-test.yml
=> Retrieve correct tag in test pypi action

neo/rawio/spikeglxrawio.py
For commercial 2.0 probes, the manual says the ADC is 12 bits, which would make the highest positive value to be 2048, not 8192, as is hardcoded in the code. In the metadata of my recordings, `imMaxInt=2048`. 
Jennifer Colonnel's code [here](https://github.com/jenniferColonell/SpikeGLX_Datafile_Tools/blob/4b6c28658b715808e4941e43d5fa0c57198b09da/Python/DemoReadSGLXData/readSGLX.py#L78C29-L78C29) uses the imMaxInt to calculate the gain factor.
=> Gain calculation for Neuropixel 2.0 might be wrong

neo/rawio/spikeglxrawio.py
The 'easy' regex `in parse_spikeglx_fname in spikeglxraio.py` expects the fname to end in .ap or .lf, which doesn't work if the input is actually an NIDaq file from SpikeGLX.
I just added another regex that works for the .nidq files, and some example filenames to comment what the regex targets.
=> Parse spikeglx nidq without gate or trigger number

neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
This is an older item that was due and is in preparation for dealing with issue #1370. 
Tests use the Pegasus 2.1.1 data already in the ephy_testing_data repository.
=> Handle Pegasus 2.1.1 Nev files and tests of same.

neo/rawio/openephysrawio.py, neo/test/rawiotest/rawio_compliance.py, neo/test/rawiotest/test_openephysrawio.py
@weiglszonja @bendichter @alejoe91 @CodyCBakerPhD 
This PR should fix the gap problem in openephys legacy format.
The old an erroreneous `ignore_timestamps_errors` is deprecated.
Now there is a gap checking when parsing the header. If gaps are detected then internally the reader go in a gap mode reading which is slower because it need np.seachrsorted at every get_analogsignal_chunk().
I propagate this on spikeinterface side here https://github.com/SpikeInterface/spikeinterface/pull/2450
=> openephys legacy format : handle gaps more correctly

.gitignore, neo/rawio/plexon2rawio/pypl2/pypl2lib.py
This is generating error when the tests are attempeded to run without wine.  I added an informative message. Plus, I also added the vscode files to the gitignore.
=> Skip plexon 2 tests when wine is not present

neo/core/baseneo.py
Fixes #1195.
Just adding a check for the key. Example from issue:
```
my_meta={(lambda a: None): 5}
```
Because the keys aren't checked this doesn't fail until writing. We should check to make sure the key is one of the [allowable annotations](https://github.com/NeuralEnsemble/python-neo/blob/c96ec936049a125d6bedfa26b67514f927bb1ab3/neo/core/baseneo.py#L14-L29).
We still have problems with writing some of the allowable annotations (see [this issue](1198)), but adding this check at least moves in the right direction.
=> Check that keys of nested dictionaries in annotations are `str`

neo/rawio/tdtrawio.py
Fixes #1369.
Based on the discussion in #1369, it appears empirically that the units for tdt are actually in uV and not in V. This just switches the unit so downstream conversions are correct.
=> TDTRawIO: Change tdt units to uV

neo/rawio/intanrawio.py
Currently, when calling `get_analog_signal_chunk` with Intan a numpy array is created an array with dtype `uint16` is created. However, some of the streams do not have that dtype and then an implicit casting that I think is buggy occurs.
This PR instead determines the dtype of the output numpy array by accessing the dtype from the corresponding memmap region.
=> IntanRawIO: type casting bug in `get_analogsignal_chunk`

neo/rawio/neuralynxrawio/neuralynxrawio.py
These changes allow use of the get_file_map method statically. This is useful for some new code which will allow generating sample dump files for use in testing without assuming particular header structure.
=> NeuralynxIO: get_file_map as static method

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/neuralynxrawio.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
This factors parsing the NlxHeader into parts and provides an option to construct without testing for time and date.
=> NeuralynxIO: Factor out header handling.

neo/rawio/neuralynxrawio/ncssections.py
Provides a module comment which lays out the structure of .Ncs files, how time gaps arise, and the challenges in identifying them.
=> Document the purpose of NcsSections module.

neo/rawio/spikeglxrawio.py
Fixes #1144.
In this case if there are no combo of .meta and .bin we raise a FileNotFoundError so that the user can double check their directory folder names. Happy to hear better ideas for this error though.
=> SpikeglxRawIO: raise error if no `.meta`-`.bin` combos of files detected

neo/rawio/spikegadgetsrawio.py, neo/test/rawiotest/test_spikegadgetsrawio.py
Updates spikegadgetsrawio.py:_parse_header() to check devices for proper dictionary keys before attempting to access them.
=> Fix issue #1432: loading Neuropixel data from SpikeGadgets session.

neo/rawio/tdtrawio.py
Fix https://github.com/NeuralEnsemble/python-neo/issues/1401
For some TDT files (from 2014 as pointed out in the issue), the channel groups info that is extracted from the Tbk file doesn't contain all expected field names. I think we should allow reading these files (they are currently not readable as they fail at `read_tbk()`) but should issue a warning.
=> Fix reading TDT files where Tbk header contains incomplete channel group info

neo/rawio/openephysrawio.py, neo/test/rawiotest/test_openephysrawio.py
Fixes #1320 
Replaces #1423 
It seems that newer versions of openephys have filenames of `xx_RhythmData_CHx` instead of `xx_CHx`. This PR switches to using pathlib for openephys + accounts for this new naming convention + more robustly deals with missing `.events` files since in fact there can also be empty `.events` files. 
We can test with these files for the new naming format.
[openephys_rhythmdata_test_nodes.zip](https://github.com/NeuralEnsemble/python-neo/files/14839537/openephys_rhythmdata_test_nodes.zip)
Also adding for changes to [OE docs](https://open-ephys.github.io/gui-docs/User-Manual/Recording-data/Open-Ephys-format.html) for those who wan to read about these changes.
=> OpenEphys: Allow for new `stream` naming convention

neo/rawio/axonrawio.py
Fixes #1434.
Still need to be tested by user in PR #1434, but this uses the string parsing strategy that pyABF came up with. License is an MIT https://github.com/swharden/pyABF/blob/main/LICENSE, and docs for his logic here: https://swharden.com/pyabf/abf2-file-format/.
Basically the issue in #1434, the device is not returned (so no `[b"AXENGN", b"clampex", b"Clampex", b"EDR3", b"CLAMPEX", b"axoscope", b"AxoScope", b"Clampfit"`]. I tested the test file locally and it seemed to run when I changed the parsing as in this PR. 
the strategy in short is to parse based \xx0\xx0 rather than trying to find the device. The string format then actually follows the correct indices as given by ADC info so we don't need to subtract one.
@shankardutt can you test from this PR with your data. I tested it …
=> AxonRawIO: Change Strings Parsing for additional formats.

neo/test/iotest/test_get_io.py
The current error is very hard to understand
```python
file_or_folder = PosixPath('non_existant_file.nix'), args = (), kwargs = {}
ios = [<class 'neo.io.nixio.NixIO'>, <class 'neo.io.nixio_fr.NixIO'>]
io = <class 'neo.io.nixio_fr.NixIO'>
def get_io(file_or_folder, *args, **kwargs):
"""
Return a Neo IO instance, guessing the type based on the filename suffix.
"""
ios = list_candidate_ios(file_or_folder)
for io in ios:
try:
return io(file_or_folder, *args, **kwargs)
except:
continue
>       raise IOError(f"Could not identify IO for {file_or_folder}")
E       OSError: Could not identify IO for non_existant_file.nix
```
It turns out this error only occurs because nixio is not installed. We should skip this test if nixio is not installed. 
The other option would be to instead give a meaningful …
=> Testing: Add skip test for non-existent writable io if nixio is not installed

doc/source/contributing.rst, neo/test/iotest/common_io_test.py, neo/test/rawiotest/common_rawio_test.py, neo/test/rawiotest/tools.py, neo/test/utils/test_datasets.py
Replaces #1263 (potentially-it's just a different strategy). Fixes #1037.
This keeps the same functional approach as before. I changed the order of the import datalad and the env variable because even if someone has datalad the env var should overrule everything else.
Then we need to skip testing download as well (which we didn't do before). If I do this then I can run and pass through all core tests without doing any of the dataset tests.
I also (and this is just me) made the env variable `NEO_TESTS_NO_NETWORK` because `NONETWORK` is hard for me to parse.
@samuelgarcia and @JuliaSprenger.
=> Testing: Skip network-dependent tests if no network access

neo/rawio/maxwellrawio.py
Fixes #1427
@sofiapuvogelvittini with this patch the behavior is the following:
- If you have multiple wells with the same recording (e.g. `well000/rec0000`, `well001/rec0000`) they will be loaded as different streams (same as before)
- If you have multiple wells with different recordings, you need to pass the `rec_name` argument to specify which recording you want to load. For example, if you have  `well000/rec0000`, `well001/rec0000` and  `well006/rec0001`, you need to specify either `rec0000` (will load `well000` and `well001`) or `rec0001` (will load `well006`).
Can you try this on your side?
=> Fix reading Maxwell MaxTwo 24-wells data

neo/rawio/spikegadgetsrawio.py
Updates spikegadgetsrawio.py:_parse_header() to read the channel (ntrode) gain scaling from the header file elements.
=> Read gain scaling from .rec header.

neo/rawio/spikeglxrawio.py, neo/test/rawiotest/test_spikeglxrawio.py
Fixes #1451 
also adding Ultra-beta variant (1121) ant NP-Opto (1300). All these models are based on NP1.0 technology
@CodyCBakerPhD
=> SpikeGLX: add Ultra and NP-Opto types

neo/rawio/neuroscoperawio.py, neo/test/rawiotest/test_neuroscoperawio.py
Need to multiply not divide by 1000 for mV scale.
=> Neuroscope: fix scale of signals.

neo/rawio/openephysrawio.py
@weiglszonja : Here this raise an error when a file is corrupted (bad timestamp)
=> Protect against corrupted channels in legacy openephys.

neo/rawio/blackrockrawio.py, neo/test/rawiotest/test_blackrockrawio.py
Fixes #1332
Blackrock's newest signal acquisition devices use nanosecond timestamps from clocks synchronized with PTP. This allows synchronization between devices that might have slightly different clock rates and not capture exactly 30_000 samples per reference second.
Individual per-sample timestamps are stored in a data header, per sample.
Previously, the presence of a header in the data block would indicate the start of a new segment, and methods would look for the header to start a new memmap. That previous solution, when applied to millions of headers in the PTP-enabled files, led to OS-level problems by creating too many memmaps.
This PR allows the new PTP-enabled NSx files to be loaded.
Note: the time range of data files no longer start at 0! They start at whatever the monotonic …
=> Add support for Blackrock NSx files with per-sample PTP nanosecond timestamps

neo/rawio/intanrawio.py, neo/test/iotest/test_intanio.py, neo/test/rawiotest/test_intanrawio.py
This will be adding support for `RHX` rhs files with a separate header for `rhs` files. We haven't officially update RHS support since RHS 1.0 and we are on 3.x so this may take a bit of work. We will add tests files soon so that we can properly test this.
TODOS
Neuroconv provenance https://github.com/catalystneuro/neuroconv/issues/789
=> IntanRawIO: Update support of `rhs` files

doc/source/authors.rst, doc/source/releases.rst, doc/source/releases/0.13.1.rst, pyproject.toml
These notes assume that #1338 gets merged before the release. If it doesn't get merged, remove the mention of BlackrockIO.
Note that I added affiliations for new contributors where I could find them. If you see yourself in the author list and there's no affiliation given, please let us know in the comments if you'd like your affiliation to be added. If there's an error in your affiliation, please also let us know.
=> Release notes for 0.13.1, plus an update to the list of authors.

neo/rawio/blackrockrawio.py
This PR is a minor fix / update to the docstring in the BlackrockRawIO object, notably:
- fixing a note that implies only 2.X formats are supported now that 3.0 is also supported
- minor fixes to the parameter listings
=> [DOC] - Minor update to BlackrockRawIO docstring

neo/rawio/spikeglxrawio.py
Some nidq.meta files do not have this field set when recording additional streams with the NIDQ interface
=> Handle empty niXDChans1 field in nidq.meta

.github/workflows/io-test.yml, neo/rawio/intanrawio.py, neo/test/iotest/test_intanio.py, neo/test/rawiotest/test_intanrawio.py
For the `header-attached` and the `one-file-per-signal` the digital channels are interleaved  and need a bitwise operators to separate the channels but this is not the case for the `one-file-per-channel` where each digital channel is separated and is already uint16 with 0 and 1s.
This PR patches this behavior so the digital channels can be correctly retrieved for the case of the `one-file-per-channel`.  Unfortunatlely, we don't have a multiple digital channels in the test examples on git to test for this behavior. Any idea on how to test for this @zm711 ?
I tested this for data that I have and it works.
=> Fix digital streams in Intan for the `one-file-per-channel` format in rhd.

.github/workflows/core-test.yml
So I added 3.12 to the matrix. 3.8 goes off support in October but by then 3.13 should be released. We probably shouldn't get too far behind testing the python versions.
Only annoying things is that because of deprecations only numpy 1.26 is compatible. But I added that to tests as well. Once we remove 3.8 this will also clean-up nicely.
=> Testing: adding python 3.12 to core tests

.github/workflows/io-test.yml, environment_testing.yml
Since python is deprecating alot of standard library stuff and we have some more legacy IOs we should probably test against multiple python versions. This tests against 
3.9, 3.10, and 3.11. We can add 3.12 to see what will break later for the IOs.
=> Testing: Run IO-tests on multiple python versions

neo/rawio/intanrawio.py
Hi,
Currently, we have a check to determine if the timestamps associated with the data exhibit discontinuities. If they do, we throw an assertion and prevent the file from being read. I believe this is beneficial as it serves as a strong signal that the user should take a closer look at the file. This assertion is warranted.
But I also believe that once we infrormed the users that there is an error we should still allow the users to open the file if so they desired. This is good for two reasons:
1) Users can use the machinery of neo to find out what might have been wrong which would be a valuable service.
2) Sometimes, there is no other way, that is, the person who ran the experiments is not longer available but people might still want to analyze the data. I think this is a user case that …
=> Add the possilibity of opening intan files even if corrupted.

neo/rawio/intanrawio.py
I made a rookie mistake in a previous PR for this line:
```python
discontinuous_timestamps = np.diff(timestamp) != 1
timestamp[discontinuous_timestamps]
```
Because diff reduces size by 1 and then the above throws an error (within the other error).
This PR solves this and improves the format in which the discontinuities are presented for the benefit of the user.
This is how things look like for a dataset with one discontinuity that I am working on.
```python
File "/home/heberto/development/spikeinterface/src/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 27, in __init__
self.neo_reader = self.get_neo_io_reader(self.NeoRawIOClass, **neo_kwargs)
File "/home/heberto/development/spikeinterface/src/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 66, in …
```
=> Improve intan reader error message for discontinuities

neo/rawio/intanrawio.py
@alejoe91 could I get a quick review of this?
Problem was that rhs doesn't use packaging.version Version so when we propagated the rhd fixes to rhs we moved Version into rhs. Testing missed this because we don't have any notch filtered rhs test files so the boolean always short circuited. 
Related to https://github.com/SpikeInterface/spikeinterface/issues/2974
=> Fix version issue for rhs

neo/rawio/neuralynxrawio/nlxheader.py
Fixes #1492
There is a typo in the date time regex used for Neuralynx headers.
The issue was introduced in commit baba820
Issue: #1492
=> Fix: fix typo in datetime regex

neo/rawio/plexon2rawio/plexon2rawio.py, neo/rawio/plexon2rawio/pypl2/pypl2lib.py
To support plexon on mac we might need to change the logic to download the corresponding ddl:
Neuroconv linked PR:
https://github.com/catalystneuro/neuroconv/issues/204
=> Plexon2 support for apple 64 bits

neo/rawio/intanrawio.py
@zm711 this is a follow-up of  https://github.com/NeuralEnsemble/python-neo/pull/1476 
This makes the extraction of the digital channels work like all the other data in neo (and therefore spikeinterface) so user does not need to do any post-processing. The post-processing was derived from the data sheet, the python [conversion script that intan provides for python](https://intantech.com/downloads.html?tabSelect=Software&yPos=68.57142639160156) and [the matlab version](https://github.com/dattalab/spike_finder/blob/master/read_Intan_RHD2000_file.m) of the same operation .
Let me know what you think.
@luiztauffer
I tested this on Nelson data like this (using this branch and from spikeinterface):
```python
from pathlib import Path
intan_data_folder = Path.home() / "Downloads" 
assert …
```
=> Intan digital channel extraction for header attached and one file per signal format

neo/io/neuralynxio.py, neo/rawio/neuralynxrawio/neuralynxrawio.py, neo/test/iotest/test_neuralynxio.py, neo/test/rawiotest/test_neuralynxrawio.py
Add a feature to allow multiple files as filename. 
Now user can create a list of filenames and assign it to the argument `filename` of `neo.io.NeuralynxIO(filename=session_data)` to read the specific files. 
If there are multiple files for a single channel, they should be consistent for all channels.
=> NeuralynxIO: support List[str] for filename parameter

neo/rawio/rawbinarysignalrawio.py
`.dat` is super common for raw binary files. If we want a raw binary reader at the neo level we should make sure it is included in possible extensions.
=> RawBinarySignalIRawIO: add `dat` extension as possibility

neo/rawio/spikegadgetsrawio.py
Only the part from #1303 that fixes the channel id issue from #1215 
Hopefully this can be merged easily
=> Minimal fix of `SpikeGadgetsRawIO` channel ID issue

neo/rawio/__init__.py
I noticed our docs were building off the deprecated function so I went to switch just the docs and decided to update the get_rawio a bit more.
The argument was filename_or_dirname, but it only checked file extensions. I extended this to accept either including not currently written files. I also added a new argument: `exclusive_rawio` if this is set to False it will return all possible rawios organized by the one that reads the most files from the directory. If it is a single file then it returns the full list unsorted.
=> Update `get_rawio` function with additional functionality

neo/rawio/plexonrawio.py, neo/test/iotest/test_plexonio.py, neo/test/rawiotest/test_plexonrawio.py
This PR solves two things:
1) Should solve https://github.com/NeuralEnsemble/python-neo/issues/1523 by using consistent stream_ids defined by plexon channel prefixes that are stable  (see [here](https://github.com/NeuralEnsemble/python-neo/pull/1495#issuecomment-2184256894)
2) It adds human readable and meaningful stream names. Right now they are called "Signal + {stream_id}" and after this PR, they will be:
```python
channel_prefix_to_stream_name = {
"WB": "WB-Wideband",
"FP": "FPl-Low Pass Filtered ",
"SP": "SPKC-High Pass Filtered",
"AI": "AI-Auxiliary Input",
}
```
Not that this moves forward the poject in https://github.com/SpikeInterface/spikeinterface/issues/3197 that aims to have "logical streams" and relegate "buffer streams" to an internal implementation detail of the raw io …
=> Fix-ate plexon signal streams

neo/rawio/medrawio.py, neo/test/rawiotest/rawio_compliance.py
Fixes #1533.
This was found in the SpikeInterface full-test suite where an option is exposed to `prefer_slice` which will attempt to give a slice for `channel_indexes`. The `get_analogsignal_chunk` docstring says that it should accept slices, so we should test that all rawios are actually compliant for this requirement. If any of rawios fail this test then we need to fix them.
=> Add test that all rawios accept `slice(None)`

neo/rawio/plexon2rawio/plexon2rawio.py
Neo fails to load a PL2 file if there are channels within the source that are disabled for recording, though otherwise enabled to be visualized. This patch fixes that. See below for details.
PL2 files are recorded using the "PlexControl" application. When setting up an experiment, the researcher has access to a number of controls for each channel. Included among these are the following two options:
(1) Enabled -- this corresponds to the "m_ChannelEnabled" flag in each channel header
(2) Record Enabled -- this corresponds to the "m_ChannelRecordingEnabled" flag in each channel header
The first option determines whether the channel's incoming data even makes it to the PlexControl application for visualization. The second option determines whether the incoming data for that channel is …
=> Fix pl2 channel enabled bug

neo/rawio/plexon2rawio/plexon2rawio.py
Same as https://github.com/NeuralEnsemble/python-neo/pull/1524 but for Plexon 2.
Also, I am exposing the number of retries as that is non-deterministic in plexon2 and that has been failing in some our CI in neuroconv because the number is too small.
=> Fix-ate plexon 2 streams

neo/test/rawiotest/common_rawio_test.py, neo/test/rawiotest/test_maxwellrawio.py
Related to the discussion in #1550
=> Make  `BaseTestRawIO` setup per class and not per test

neo/rawio/brainvisionrawio.py, neo/test/rawiotest/test_brainvisionrawio.py
The primary change allows channel descriptions in the header .vhdr file to conform to specification with some defaults for columns.
The test change simply tests the new files in https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/140 , which should be merged before this.
=> Improved brainvision header parsing.

neo/rawio/intanrawio.py
Fixes #1556 
Data before fix:
Data after fix:
Basically, since Intan was designed to be easily read with Matlab (their example work is to use `fread` which is column-major reading) we should make our memmap with `order='F'`.
@h-mayorquin want to look over this quickly and @alejoe91 I think this can be a quick review as long as everyone is agreed. See the linked issue for more information.
Can you test this @Tevin-yue?
NOTE: this is simulated data so it should look like a repeating motif of simulated "spikes".
=> IntanRawIO: Fix memmap order for Intan one-file-per-stream

.github/workflows/core-test.yml, pyproject.toml
Since 3.8 goes EOL in October we should be good to drop this.
=> Drop python 3.8

neo/rawio/neuronexusrawio.py
@alejoe91, if you have a moment this is a quick review.
Discovered here: https://github.com/SpikeInterface/spikeinterface/actions/runs/11106106976/job/30853717171?pr=3235
Should be `shape[0]` instead of `size` which is (shape[0] x shape[1]).
=> NeuroNexusRawIO: fix the get_signal_size

.github/workflows/core-test.yml, pyproject.toml
See comment [here](https://github.com/NeuralEnsemble/python-neo/pull/1573#issuecomment-2383263062) and resummarized below:
[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) + 1 year policy, we should be on Python 3.9+ now. Also NumPy 1.22+
=> Drop NumPy < 1.22.4

neo/rawio/plexonrawio.py
@h-mayorquin could I have you give this a quick read through. Then we can have Sam merge it later.
Error here:
https://readthedocs.org/projects/neo/builds/25985599/
=> PlexonIO: Fix another plexon overflow

neo/rawio/openephysbinaryrawio.py, neo/test/rawiotest/common_rawio_test.py, neo/test/rawiotest/test_openephysbinaryrawio.py
Addressing #1437.
Currently, all the logic in the events parser for OpenEphys data assumes that there is a single stream of events (simply positive or negative `states`), and it breaks down when acquiring multiple digital signals at once (`states` having different absolute values for different channels).
This is a simple fix that looks for rising and falling edges separately for each of the digital channels.
Add simple testing relying on existing test data, which fails before the fix and passes afterwards.
=> OpenEphysBinaryRawIO: Fixing ttl multichan

neo/rawio/plexonrawio.py
This should fix the errors in https://github.com/NeuralEnsemble/python-neo/pull/1612.
At least for Plexon.
=> Fix overflow of Plexon in numpy 2.0

neo/io/nwbio.py
```
self = <[AttributeError("'TimeSeries' object has no attribute '_AbstractContainer__name'") raised in repr()] TimeSeries object at 0x7f032efad6a0>
kwargs = {'name': 'First block : segment0 Signal_a None 0'}
name = 'First block : segment0 Signal_a None 0'
@docval({'name': 'name', 'type': str, 'doc': 'the name of this container'})
def __init__(self, **kwargs):
name = getargs('name', kwargs)
if ('/' in name or ':' in name) and not self._in_construct_mode:
>           raise ValueError(f"name '{name}' cannot contain a '/' or ':'")
E           ValueError: name 'First block : segment0 Signal_a None 0' cannot contain a '/' or ':'
```
from here
```
/usr/share/miniconda/envs/neo-test-env/lib/python3.9/site-packages/hdmf/utils.py:668: in func_call
return func(args[0], **pargs)
```
Fixes part of …
=> Fix NWB parsing from pynwb/hmdf

.github/workflows/io-test.yml
This will fail until we figure out #1619 and #1618. Then this will fix #1618.
We are still having issues with python version so instead I add an explicit step to set our python version number in the environment. I'm not 100% sure this will work. I think the ideal scenario would be to actually create different cached environments for python versions instead so I might try that strategy in parallel in which case we could close this PR. Opinions?
=> Fix setting python version for environment in CI

neo/rawio/spikeglxrawio.py, neo/test/rawiotest/test_spikeglxrawio.py
Should fix #1606
To solve #1606 this does two things:
1) It calculates device (probe) index from the metadata instead of relying on file parsing as we currently do. 
2) When the gate, port and dock are not available in the metadata it parses the filename as named in the metadata (as that was the original one) instead of from the filepath in the system as we are currently doing.
Both things should make the reader more robust. 
I am preparing some data for gin where the filename was changed. I will change this from draft once I add that.
=> Open folders with user altered filenames in SpikeGLX

neo/rawio/spikeglxrawio.py, neo/test/rawiotest/test_spikeglxrawio.py
=> Add timing metadata for `SpikeGLXRawIO`

neo/core/analogsignal.py, neo/core/imagesequence.py, neo/core/irregularlysampledsignal.py, neo/core/spiketrain.py
Fixes #1596 
In the linked issue it was indicated that a deprecation should not raise an error and instead should be a warning. Since we decided on this soft error which can be switched to warning by using None, I tried to improve the messaging. What do you think about this @sanjayankur31?
We need to wait for #1619 for testing to work for this.
This is ready to be reviewed now!
=> Improve `copy` deprecation message

.github/workflows/io-test.yml, environment_testing.yml
We also need to start seeing which IOs are potentially not 2.0 ready. This is just a draft to start assessing this.
This is much better than I was expecting :) 
```
FAILED neo/test/rawiotest/test_blackrockrawio.py::TestBlackrockRawIO::test_compare_blackrockio_with_matlabloader - KeyError: np.int64(-1)
FAILED neo/test/rawiotest/test_blackrockrawio.py::TestBlackrockRawIO::test_compare_blackrockio_with_matlabloader_v21 - OverflowError: Python integer -1 out of bounds for uint16
FAILED neo/test/rawiotest/test_blackrockrawio.py::TestBlackrockRawIO::test_read_all - KeyError: np.int64(-1)
FAILED neo/test/rawiotest/test_plexonrawio.py::TestPlexonRawIO::test_read_all - OverflowError: Python integer 4294967296 out of bounds for uint16
```
=> NumPy 2.0 support for IOs

.github/workflows/io-test.yml, environment_testing.yml, neo/rawio/blackrockrawio.py
This depend on #1614 
@zm711 : I am super procrastinator but finally I did it.
=> Fix blackrock numpy2

neo/core/irregularlysampledsignal.py, neo/core/segment.py, neo/core/spiketrain.py, neo/core/view.py, neo/io/__init__.py, neo/rawio/__init__.py, neo/rawio/cedrawio.py, neo/rawio/elanrawio.py, neo/rawio/intanrawio.py, neo/rawio/maxwellrawio.py, neo/rawio/neuronexusrawio.py, neo/rawio/rawbinarysignalrawio.py, neo/rawio/rawmcsrawio.py, neo/rawio/spike2rawio.py, neo/rawio/winwcprawio.py
While dealing with the documentation meltdown the warnings were making it hard to see the errors, so I wanted to cleanup some of the warnings.
=> Fix docutil parsing errors in code base

neo/io/neomatlabio.py
Fix issue https://github.com/NeuralEnsemble/python-neo/issues/1636.
=> Fix NeoMatlabIO write_block unused kargs

.github/workflows/caches_cron_job.yml
Just checked our actions and realized we were creating a cache already. To be environmentally friendly let's not do this cron job while we decide whether to permanently remove the conda env cache.
for @samuelgarcia, but @alejoe91 since you'll see this first (most likely) feel free to make sure I didn't mess it up.
We should keep this in mind for #1628.
=> Stop Cron Job for Creating Conda Env

neo/rawio/blackrockrawio.py
Fixes int overflow for big blackrock files. Error trace:
```
Traceback (most recent call last):
File "/disk/scratch/nkudryas/StimIO/BlackRock_US_dataset/bin_spikes.py", line 54, in <module>
recording = read_blackrock(file_path=filename) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/disk/scratch/nkudryas/StimIO/spikeinterface/src/spikeinterface/extractors/neoextractors/blackrock.py", line 52, in __init__
NeoBaseRecordingExtractor.__init__(
File "/disk/scratch/nkudryas/StimIO/spikeinterface/src/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 188, in __init__
_NeoBaseExtractor.__init__(self, block_index, **neo_kwargs)
File "/disk/scratch/nkudryas/StimIO/spikeinterface/src/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 27, in __init__
self.neo_reader = …
```
=> Fix int overflow in blackrock

neo/rawio/openephysbinaryrawio.py
falling and rising indices of events must be arrays of integers, even if empty, otherwise it fails when trying to use them to compute durations. This issue is only triggered when trying to access recordings without any events. The small change was enough to fix the issue in the dataset I was exploring but there might be other places that need updating.
=> Fix: In openephysbinaryrawio.py

neo/rawio/tdtrawio.py
@samuelgarcia @alejoe91 
This is from this error in SpikeInterface:
https://github.com/SpikeInterface/spikeinterface/issues/3025
The thing is that for streams (`StoreName`) that have no matching data for the channel we assign the dtype as `int` and then transform it to string when we cast to the signal_channel_dtype for the struct.
This leads to the following error:
```python
_dtype = "int"
_dtype_as_string = str(_dtype)
np.dtype(_dtype_as_string)
TypeError: data type "<class 'int'>" not understood
```
The solution is to use `"int"` as a placeholder instead. 
I also changed some values that were used as numpy scalar as they will probably introduce bugs as they have done in the past.
=> Fix tdt default case dtype

neo/rawio/intanrawio.py
Hey @zm711 
I realize that we don't this. I would like to have a method like this exposed. I am fine with private and I can keep track of if if necessary but I think public is fine.
What do you think?
=> Add utility method to get timestamps on Intan base

neo/rawio/maxwellrawio.py
=> Fix Maxwell IO 

neo/io/__init__.py, neo/io/baseio.py, neo/io/nixio.py, neo/io/stimfitio.py
Worked on this for spikeinterface so also doing this here. As of python 3.8 this is desired way to verify packages. Also as of python 3.10 they completely removed sequence from collections so I think we should be fine to remove that try-except.
=> Cleanup import to use `importlib.util.find_spec`

neo/rawio/intanrawio.py, pyproject.toml
Should fix #1664
The deprecation was delayed in the latest version:
https://setuptools.pypa.io/en/stable/history.html?utm_source=chatgpt.com#v78-0-2
But they are still on the process of making a new release.
https://github.com/pypa/setuptools/commit/3c88de1c62420c1e0161f48e34af6424ac009aa5
Should be ready soon.
=> Update setuptools on `pyproject.toml`

neo/test/generate_datasets.py
Basically we have stochastic failures in this test https://github.com/NeuralEnsemble/python-neo/blob/74c97fdf4b549d632c1cfb85b9ab79cdab8f1a6b/neo/test/coretest/test_segment.py#L46-L66
because currently we sometimes generate a completely empty segment with nothing in it so the list of `t_starts` is empty which causes the `min` function to fail. This makes us have to re-run the test CI to  get a result. Instead I made the function recursive such that each segment needs to have at least one of the types of children objects for testing purposes (to be clear it just needs one so if the n_child is 0 for all types of children then it fails which is what causes the test to stochastically fail). 
The other option would be to change the test to accept the fact we have an empty segment. So let me …
=> Prevent empty seg in `random_segment` which causes tests to fail stochastically

.github/workflows/io-test.yml, neo/test/rawiotest/common_rawio_test.py, neo/test/rawiotest/tools.py, pyproject.toml
I noticed our 3.12 testing is just skipping rather than running. I'll track down what is happening here.
=> Fix ci testing-datalad install for python 3.12 + git-annex

neo/rawio/spikeglxrawio.py, neo/test/rawiotest/test_spikeglxrawio.py
Should fix #1661
See discussion here: #1656
Added a test as @zm711 requested.
This is restoring some behavior that we lost after #1608
Plus, reading the metadata history changes here:
https://billkarsh.github.io/SpikeGLX/help/parsing/
Calculating `device_index` through the original file name is robust up till the phase 3A whereas the current `probe_index` calculation might fail for some phases. So I think this is a good improvement overall and simplifies the code.
=> Fix spikeglx stream for isolated folder from multi probe case.

neo/rawio/blackrockrawio.py, neo/rawio/spikegadgetsrawio.py, neo/rawio/spikeglxrawio.py, neo/test/generate_datasets.py, neo/test/rawiotest/test_spikegadgetsrawio.py
@alejoe91 we both know Sam will close this :) :P 
Basically the issue was the new spike gadgets test for missing channels was going to lead to horrific formatting, so I had to close black formatting and add in the `fmt: off` in order to prevent that going forward :)
=> Black Formatting Manually

neo/rawio/neuralynxrawio/neuralynxrawio.py
This is part of https://github.com/NeuralEnsemble/python-neo/issues/1678 but does not solve it completly.
=> Remove numpy scalar from stream name representation for neuralynx

neo/rawio/blackrockrawio.py
Make this available without the need to parse the header.
https://github.com/SpikeInterface/spikeinterface/pull/3843
=> Blackrock make sampling rate a class attribute.

neo/rawio/neuralynxrawio/nlxheader.py
Fixes #1675 
This is based on what a user shared.
We can see in the header we were missing the (h:m:s.ms) for the regex and were missing the closed time. Let's see what happens with the test suite.
=> Update neuralynx regex for 5.6.0

codemeta.json, doc/source/authors.rst, doc/source/conf.py, doc/source/releases.rst, doc/source/releases/0.14.1.rst, pyproject.toml
Just so we have everything ready after our meeting. We've had touchups to 9 IOs so I think a point release is merited. We will see if we want to hold off a week after the meeting as I can imagine 2-3 more PRs for IOs that would like to be included.
Also I have the authors updated and the codemeta.json, but I want to wait to commit those until I hear back from one more person about being included.
I've fixed the milestones on issues and PRs already for 0.14.1.
=> Prep Release 0.14.1

.github/workflows/io-test.yml, neo/rawio/intanrawio.py
kitenet is forbidden access now so we need to switch.
=> Fix linux datalad-git-annex install

neo/rawio/blackrockrawio.py
=> Blackrock rawio fix overflow

neo/rawio/blackrockrawio.py
Added a shape parameter to avoid the error #1704 
Fix #1704
=> BlackRock: shape parameter for memap

.github/workflows/io-test.yml, .github/workflows/plexon2-testing.yml, neo/test/iotest/test_plexon2io.py, neo/test/rawiotest/test_plexon2rawio.py
Since plexon2 is causing extreme flakiness in our test suite I think this will switch it to a cron job as well as let us manually run for plexon2 PRs.
=> Switch Plexon2 to a cron job/ workflow dispatch

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
This moves much of the conversions and setting from read_properties into separate methods. Also make the acquisition type a proper IntEnum rather than simply strings.
This is in preparation for major changes to how the header entries are parsed to be more flexible.
=> Refactor Neuralynx file header processing

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
Continues the process of generalizing the header processing. Builds on refactorHeaderProcessing and should merge once that is in place.
I am trying to keep things in smaller reviewable chunks though that does depend then on the reviews.
=> [NeuralynxRawIO] Generalize header processing

neo/rawio/neuralynxrawio/ncssections.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
At long last, replaced the complicated header dictionaries with more general patterns and checks. There are a few more tweaks on this that will be nice but this is a good chunk. As before, depends on the prior chain with NeuraviewTestAndRefactor.
=> [NeuralynxRawIO] Clean time parsing

neo/rawio/spikeglxrawio.py, neo/test/rawiotest/test_spikeglxrawio.py
Should close #1684
Needs the gin test data that is in a PR right now:
https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/156#
=> SpikeGLX: Add one box reading

neo/rawio/neuralynxrawio/neuralynxrawio.py, neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py, pyproject.toml
We previously had `python-dateutil` has a dependency of one of our dependencies. I didn't track which one, but that means when you do a non-core install you have `dateutil` automatically installed. This means that in #1571 we assumed that we had this package around. This broke our core testing so this PR does 2 things:
1) Make this dependency explicit for neuralynx
2) moves testing into the function so that core tests don't break.
=> NeuralynxIO: Add `python-dateutil` dependency 

neo/rawio/neuronexusrawio.py
I first implemented this before the buffer api and since this is one buffer for all streams we left them all packed together. Now that we have the buffer api we should divide these streams into
ephys data (called analog in allego docs)
din
dout
aux
~~No rush on this so we can wait until we figure out plexon2 tests.~~
=> NeuroNexusIO: Add in appropriate streams to go with buffer API

CODE_OF_CONDUCT.md, README.rst, doc/source/governance.rst
As decided in the last Neo Core Meeting, this MR replaces the current CoC with the NumFOCUS CoC. As recommended by NumFOCUS the MR does not copy the CoC, but rather links to the NumFOCUS document.
Furthermore this implies that Neo is now employing the NumFOCUS workflow for reporting CoC violations and NumFOCUS will advise Neo maintainers on how to proceed in case of a CoC violation.
The CoC also applies for events organized by the Neo Team, where the CoC will be introduced in the beginning of the event and a dedicated CoC contact person will be assigned.
Once this MR is merged I we will also announce the CoC change on the community mailing list.
=> Adopt the NumFOCUS Code of Conduct

.github/workflows/plexon2-testing.yml
Windows tests failing due to bad install. Our testing is only written to test wine on linux. So remove windows-latest from cron.
=> Fix Plexon2 Cron: Remove Windows from Cron job

neo/rawio/biocamrawio.py
=> Fix offset when using synthetic noise with BioCAM's sparse compression

neo/io/kwikio.py, neo/test/iotest/test_kwikio.py
@alejoe91 @samuelgarcia @h-mayorquin,
So kwik hasn't been updated in 6 years and it is using code that has now been removed from NumPy breaking our testing. I've added in this strategy to block usage for inappropriate numpy unless you all think there is a better strategy? I make the error occur at init of the class, but I guess I could do some sort of import level magic.
=> KwikIO: Limit IO to numpy < 2.3.0

neo/rawio/neuronexusrawio.py
typo only triggered when data is corrupted/files are mixed. Caught my eye haha.
=> NeuroNexusRawIO: Fix bug in timestamp validation error

neo/rawio/neuralynxrawio/nlxheader.py, neo/test/rawiotest/test_neuralynxrawio.py
This is an issue with the same data discussed in #1778 
```
.
├── CSC145.ncs
├── CSC146.ncs
└── csc23_100.ncs
```
The problem is that the `DspFilterDelay_µs` is sometimes encoded in latin-1 and sometimes encoded in utf8. This means that we decoding with the current method (latin-1) sometimes this specific property is read without the micro symbol and creates a key error here:
https://github.com/NeuralEnsemble/python-neo/blob/72ec76a0cc30ebdaf321a91460b51632959ee5cb/neo/rawio/neuralynxrawio/neuralynxrawio.py#L543-L548
when aggregating annotations over the channels.
This patch fixes this by using a regex to match what Latin-1 will read if the data is encoded as UTF-8.
The deeper problem is that Neuralynx does not really maintain its promise of ASCII headers.
@weiglszonja
=> Fix, Neuralynx encoding error

neo/rawio/neuralynxrawio/neuralynxrawio.py, neo/test/rawiotest/test_neuralynxrawio.py
Users sometimes place extra directories and files under the Neuralynx root. Today, we exclude by extension, but in “one-dir” mode the reader asserts that every entry must be a file, which raises an error:
https://github.com/NeuralEnsemble/python-neo/blob/72ec76a0cc30ebdaf321a91460b51632959ee5cb/neo/rawio/neuralynxrawio/neuralynxrawio.py#L217-L231
We should fix this to (1) make the workflow more forgiving for users and (2) align behavior with `include_filenames`, which already allows nested folders.
Proposed change: restructure file discovery into three steps.
1) Gather candidates by mode:
- **multiple-files**: validate existence only for the explicitly provided filenames.
- **one-dir**: list directory entries and keep only regular files via `Path.is_file()` (silently ignore …
=> Fix  `NeuralynxRawIO`  reading in one-dir mode with nested directories

neo/rawio/brainvisionrawio.py
This fixes a problem where BrainVision files that had been renamed but were not patched by the user will fail to import.
BrainVision EEG files come in triples, as in `myfile.vhdr`, `myfile.eeg`, and `myfile.vmrk`.
The problem is that the `.vdhr` file has a textual reference to the sidecar `.vmrk` and `.eeg` files, as in the following example:
File `l3_s02b12c01.vmrk`:
```ini
[Common Infos]
Codepage=UTF-8
DataFile=l3_s02b12c01.eeg
MarkerFile=l3_s02b12c01.vmrk
```
... but when users rename all 3 files (eg to fix a mistyped subject/session name or etc.), the resulting files can no longer be imported with Neo, unless the user also manually edits the `.vhdr` file and fixes the reference.
This is the same feature also found in some other BV importers, e.g. [the …
=> fix handling of broken file references in brainvisionrawio
